/*
 * Copyright 2022-2025 Morse Micro
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-MorseMicroCommercial
 *
 * This file is autogenerated. Do not edit by hand.
 */



#pragma once

#include "mmwlan.h"
#include "mmwlan_stats.h"
#include "umac/data/umac_data.h"


void umac_stats_init(struct umac_data *umacd);


void umac_stats_dump(struct umac_data *umacd);


enum mmwlan_status umac_stats_get_all(struct umac_data *umacd, struct mmwlan_stats_umac_data *dest);


enum mmwlan_status umac_stats_clear_all(struct umac_data *umacd);


int umac_stats_serialise(struct umac_data *umacd, uint8_t *buf, size_t buf_size);


void umac_stats_update_last_tx_time(struct umac_data *umacd);


uint32_t umac_stats_get_last_tx_time(struct umac_data *umacd);


void umac_stats_clear_last_tx_time(struct umac_data *umacd);


void umac_stats_increment_datapath_rxq_frames_dropped(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_rxq_frames_dropped(struct umac_data *umacd);


void umac_stats_clear_datapath_rxq_frames_dropped(struct umac_data *umacd);


void umac_stats_increment_datapath_txq_frames_dropped(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_txq_frames_dropped(struct umac_data *umacd);


void umac_stats_clear_datapath_txq_frames_dropped(struct umac_data *umacd);


void umac_stats_update_connect_timestamp(struct umac_data *umacd, uint32_t idx);


void umac_stats_clear_connect_timestamps(struct umac_data *umacd);


void umac_stats_set_rssi(struct umac_data *umacd, int16_t rssi);


int16_t umac_stats_get_rssi(struct umac_data *umacd);


void umac_stats_clear_rssi(struct umac_data *umacd);


void umac_stats_increment_hw_restart_counter(struct umac_data *umacd);


uint16_t umac_stats_get_hw_restart_counter(struct umac_data *umacd);


void umac_stats_clear_hw_restart_counter(struct umac_data *umacd);


void umac_stats_increment_num_scans_complete(struct umac_data *umacd);


uint16_t umac_stats_get_num_scans_complete(struct umac_data *umacd);


void umac_stats_clear_num_scans_complete(struct umac_data *umacd);


void umac_stats_update_datapath_rxq_high_water_mark(struct umac_data *umacd, uint8_t datapath_rxq);


uint8_t umac_stats_get_datapath_rxq_high_water_mark(struct umac_data *umacd);


void umac_stats_clear_datapath_rxq_high_water_mark(struct umac_data *umacd);


void umac_stats_update_datapath_txq_high_water_mark(struct umac_data *umacd, uint8_t datapath_txq);


uint8_t umac_stats_get_datapath_txq_high_water_mark(struct umac_data *umacd);


void umac_stats_clear_datapath_txq_high_water_mark(struct umac_data *umacd);


void umac_stats_update_datapath_rx_mgmt_q_high_water_mark(struct umac_data *umacd,
                                                          uint8_t datapath_rx_mgmt_q);


uint8_t umac_stats_get_datapath_rx_mgmt_q_high_water_mark(struct umac_data *umacd);


void umac_stats_clear_datapath_rx_mgmt_q_high_water_mark(struct umac_data *umacd);


void umac_stats_increment_datapath_rx_ccmp_failures(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_rx_ccmp_failures(struct umac_data *umacd);


void umac_stats_clear_datapath_rx_ccmp_failures(struct umac_data *umacd);


void umac_stats_increment_datapath_driver_rx_alloc_failures(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_driver_rx_alloc_failures(struct umac_data *umacd);


void umac_stats_clear_datapath_driver_rx_alloc_failures(struct umac_data *umacd);


void umac_stats_increment_datapath_driver_rx_read_failures(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_driver_rx_read_failures(struct umac_data *umacd);


void umac_stats_clear_datapath_driver_rx_read_failures(struct umac_data *umacd);


void umac_stats_update_datapath_rx_reorder_list_high_water_mark(struct umac_data *umacd,
                                                                uint8_t datapath_rx_reorder_list);


uint8_t umac_stats_get_datapath_rx_reorder_list_high_water_mark(struct umac_data *umacd);


void umac_stats_clear_datapath_rx_reorder_list_high_water_mark(struct umac_data *umacd);


void umac_stats_increment_datapath_rx_reorder_overflow(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_rx_reorder_overflow(struct umac_data *umacd);


void umac_stats_clear_datapath_rx_reorder_overflow(struct umac_data *umacd);


void umac_stats_increment_datapath_rx_reorder_timedout(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_rx_reorder_timedout(struct umac_data *umacd);


void umac_stats_clear_datapath_rx_reorder_timedout(struct umac_data *umacd);


void umac_stats_increment_datapath_rx_reorder_outdated_drops(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_rx_reorder_outdated_drops(struct umac_data *umacd);


void umac_stats_clear_datapath_rx_reorder_outdated_drops(struct umac_data *umacd);


void umac_stats_increment_datapath_rx_reorder_retransmit_drops(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_rx_reorder_retransmit_drops(struct umac_data *umacd);


void umac_stats_clear_datapath_rx_reorder_retransmit_drops(struct umac_data *umacd);


void umac_stats_increment_datapath_rx_reorder_total(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_rx_reorder_total(struct umac_data *umacd);


void umac_stats_clear_datapath_rx_reorder_total(struct umac_data *umacd);


void umac_stats_increment_timeouts_fired(struct umac_data *umacd, uint32_t step);


uint32_t umac_stats_get_timeouts_fired(struct umac_data *umacd);


void umac_stats_clear_timeouts_fired(struct umac_data *umacd);


void umac_stats_increment_datapath_driver_tx_skbq_timeout(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_driver_tx_skbq_timeout(struct umac_data *umacd);


void umac_stats_clear_datapath_driver_tx_skbq_timeout(struct umac_data *umacd);


void umac_stats_increment_datapath_driver_tx_pending_status_timeout(struct umac_data *umacd);


uint32_t umac_stats_get_datapath_driver_tx_pending_status_timeout(struct umac_data *umacd);


void umac_stats_clear_datapath_driver_tx_pending_status_timeout(struct umac_data *umacd);

