/*
 * Copyright 2022-2025 Morse Micro
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-MorseMicroCommercial
 *
 * This file is autogenerated. Do not edit by hand.
 */

#include "umac_stats.h"

#include "mmlog.h"
#include "mmutils.h"

void umac_stats_init(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);
    memset(data, 0, sizeof(*data));
}

void umac_stats_dump(struct umac_data *umacd)
{
#if MMLOG_LEVEL == MMLOG_LEVEL_OFF
    MM_UNUSED(umacd);
#else
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);
    MMLOG_APP("Stats: %lu %lu %lu [ %lu %lu %lu %lu %lu %lu %lu %lu %lu %lu ] %d %u %u %u %u %u "
              "%lu %lu %lu %u %lu %lu %lu %lu %lu %lu %lu %lu\n",
              data->last_tx_time,
              data->datapath_rxq_frames_dropped,
              data->datapath_txq_frames_dropped,
              data->connect_timestamp[0],
              data->connect_timestamp[1],
              data->connect_timestamp[2],
              data->connect_timestamp[3],
              data->connect_timestamp[4],
              data->connect_timestamp[5],
              data->connect_timestamp[6],
              data->connect_timestamp[7],
              data->connect_timestamp[8],
              data->connect_timestamp[9],
              data->rssi,
              data->hw_restart_counter,
              data->num_scans_complete,
              data->datapath_rxq_high_water_mark,
              data->datapath_txq_high_water_mark,
              data->datapath_rx_mgmt_q_high_water_mark,
              data->datapath_rx_ccmp_failures,
              data->datapath_driver_rx_alloc_failures,
              data->datapath_driver_rx_read_failures,
              data->datapath_rx_reorder_list_high_water_mark,
              data->datapath_rx_reorder_overflow,
              data->datapath_rx_reorder_timedout,
              data->datapath_rx_reorder_outdated_drops,
              data->datapath_rx_reorder_retransmit_drops,
              data->datapath_rx_reorder_total,
              data->timeouts_fired,
              data->datapath_driver_tx_skbq_timeout,
              data->datapath_driver_tx_pending_status_timeout);
#endif
}

enum mmwlan_status umac_stats_get_all(struct umac_data *umacd, struct mmwlan_stats_umac_data *dest)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);
    memcpy(dest, data, sizeof(*dest));
    return MMWLAN_SUCCESS;
}

enum mmwlan_status umac_stats_clear_all(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);
    memset(data, 0, sizeof(*data));
    return MMWLAN_SUCCESS;
}


static bool append_tlv(uint8_t *buf,
                       size_t buf_size,
                       size_t *offset,
                       uint16_t type,
                       const uint8_t *value,
                       size_t value_size)
{
#define TLV_HDR_SIZE (4)
    if (*offset + TLV_HDR_SIZE + value_size > buf_size)
    {
        return false;
    }

    buf[*offset + 0] = type;
    buf[*offset + 1] = type >> 8;
    buf[*offset + 2] = value_size;
    buf[*offset + 3] = value_size >> 8;
    memcpy(buf + *offset + 4, value, value_size);

    *offset += TLV_HDR_SIZE + value_size;
    return true;
}

int umac_stats_serialise(struct umac_data *umacd, uint8_t *buf, size_t buf_size)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);
    size_t offset = 0;
    bool ok = true;

    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          1,
                          (const uint8_t *)&data->last_tx_time,
                          sizeof(data->last_tx_time));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          2,
                          (const uint8_t *)&data->datapath_rxq_frames_dropped,
                          sizeof(data->datapath_rxq_frames_dropped));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          3,
                          (const uint8_t *)&data->datapath_txq_frames_dropped,
                          sizeof(data->datapath_txq_frames_dropped));
    ok = ok &&
         append_tlv(buf, buf_size, &offset, 4, (const uint8_t *)&data->rssi, sizeof(data->rssi));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          5,
                          (const uint8_t *)&data->datapath_rxq_high_water_mark,
                          sizeof(data->datapath_rxq_high_water_mark));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          6,
                          (const uint8_t *)&data->datapath_txq_high_water_mark,
                          sizeof(data->datapath_txq_high_water_mark));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          7,
                          (const uint8_t *)&data->hw_restart_counter,
                          sizeof(data->hw_restart_counter));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          8,
                          (const uint8_t *)data->connect_timestamp,
                          sizeof(data->connect_timestamp));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          9,
                          (const uint8_t *)&data->num_scans_complete,
                          sizeof(data->num_scans_complete));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          10,
                          (const uint8_t *)&data->datapath_rx_mgmt_q_high_water_mark,
                          sizeof(data->datapath_rx_mgmt_q_high_water_mark));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          11,
                          (const uint8_t *)&data->datapath_rx_ccmp_failures,
                          sizeof(data->datapath_rx_ccmp_failures));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          12,
                          (const uint8_t *)&data->datapath_driver_rx_alloc_failures,
                          sizeof(data->datapath_driver_rx_alloc_failures));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          13,
                          (const uint8_t *)&data->datapath_driver_rx_read_failures,
                          sizeof(data->datapath_driver_rx_read_failures));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          14,
                          (const uint8_t *)&data->datapath_rx_reorder_list_high_water_mark,
                          sizeof(data->datapath_rx_reorder_list_high_water_mark));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          15,
                          (const uint8_t *)&data->datapath_rx_reorder_overflow,
                          sizeof(data->datapath_rx_reorder_overflow));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          16,
                          (const uint8_t *)&data->datapath_rx_reorder_timedout,
                          sizeof(data->datapath_rx_reorder_timedout));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          17,
                          (const uint8_t *)&data->datapath_rx_reorder_outdated_drops,
                          sizeof(data->datapath_rx_reorder_outdated_drops));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          18,
                          (const uint8_t *)&data->datapath_rx_reorder_retransmit_drops,
                          sizeof(data->datapath_rx_reorder_retransmit_drops));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          19,
                          (const uint8_t *)&data->datapath_rx_reorder_total,
                          sizeof(data->datapath_rx_reorder_total));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          20,
                          (const uint8_t *)&data->timeouts_fired,
                          sizeof(data->timeouts_fired));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          21,
                          (const uint8_t *)&data->datapath_driver_tx_skbq_timeout,
                          sizeof(data->datapath_driver_tx_skbq_timeout));
    ok = ok && append_tlv(buf,
                          buf_size,
                          &offset,
                          22,
                          (const uint8_t *)&data->datapath_driver_tx_pending_status_timeout,
                          sizeof(data->datapath_driver_tx_pending_status_timeout));
    if (ok)
    {
        return offset;
    }
    else
    {
        return -1;
    }
}

void umac_stats_update_last_tx_time(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->last_tx_time = mmosal_get_time_ms();
}

uint32_t umac_stats_get_last_tx_time(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->last_tx_time;
}

void umac_stats_clear_last_tx_time(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->last_tx_time = 0;
}

void umac_stats_increment_datapath_rxq_frames_dropped(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rxq_frames_dropped++;
}

uint32_t umac_stats_get_datapath_rxq_frames_dropped(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_rxq_frames_dropped;
}

void umac_stats_clear_datapath_rxq_frames_dropped(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rxq_frames_dropped = 0;
}

void umac_stats_increment_datapath_txq_frames_dropped(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_txq_frames_dropped++;
}

uint32_t umac_stats_get_datapath_txq_frames_dropped(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_txq_frames_dropped;
}

void umac_stats_clear_datapath_txq_frames_dropped(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_txq_frames_dropped = 0;
}

void umac_stats_update_connect_timestamp(struct umac_data *umacd, uint32_t idx)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    MMOSAL_ASSERT(idx < MMWLAN_STATS_CONNECT_TIMESTAMP_N_ENTRIES);

    data->connect_timestamp[idx] = mmosal_get_time_ms();
}

void umac_stats_clear_connect_timestamps(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    memset(data->connect_timestamp, 0, sizeof(data->connect_timestamp));
}

void umac_stats_set_rssi(struct umac_data *umacd, int16_t rssi)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->rssi = rssi;
}

int16_t umac_stats_get_rssi(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->rssi;
}

void umac_stats_clear_rssi(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->rssi = 0;
}

void umac_stats_increment_hw_restart_counter(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->hw_restart_counter++;
}

uint16_t umac_stats_get_hw_restart_counter(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->hw_restart_counter;
}

void umac_stats_clear_hw_restart_counter(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->hw_restart_counter = 0;
}

void umac_stats_increment_num_scans_complete(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->num_scans_complete++;
}

uint16_t umac_stats_get_num_scans_complete(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->num_scans_complete;
}

void umac_stats_clear_num_scans_complete(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->num_scans_complete = 0;
}

void umac_stats_update_datapath_rxq_high_water_mark(struct umac_data *umacd, uint8_t datapath_rxq)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);
    if (datapath_rxq > data->datapath_rxq_high_water_mark)
    {
        data->datapath_rxq_high_water_mark = datapath_rxq;
    }
}

uint8_t umac_stats_get_datapath_rxq_high_water_mark(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_rxq_high_water_mark;
}

void umac_stats_clear_datapath_rxq_high_water_mark(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rxq_high_water_mark = 0;
}

void umac_stats_update_datapath_txq_high_water_mark(struct umac_data *umacd, uint8_t datapath_txq)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);
    if (datapath_txq > data->datapath_txq_high_water_mark)
    {
        data->datapath_txq_high_water_mark = datapath_txq;
    }
}

uint8_t umac_stats_get_datapath_txq_high_water_mark(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_txq_high_water_mark;
}

void umac_stats_clear_datapath_txq_high_water_mark(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_txq_high_water_mark = 0;
}

void umac_stats_update_datapath_rx_mgmt_q_high_water_mark(struct umac_data *umacd,
                                                          uint8_t datapath_rx_mgmt_q)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);
    if (datapath_rx_mgmt_q > data->datapath_rx_mgmt_q_high_water_mark)
    {
        data->datapath_rx_mgmt_q_high_water_mark = datapath_rx_mgmt_q;
    }
}

uint8_t umac_stats_get_datapath_rx_mgmt_q_high_water_mark(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_rx_mgmt_q_high_water_mark;
}

void umac_stats_clear_datapath_rx_mgmt_q_high_water_mark(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_mgmt_q_high_water_mark = 0;
}

void umac_stats_increment_datapath_rx_ccmp_failures(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_ccmp_failures++;
}

uint32_t umac_stats_get_datapath_rx_ccmp_failures(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_rx_ccmp_failures;
}

void umac_stats_clear_datapath_rx_ccmp_failures(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_ccmp_failures = 0;
}

void umac_stats_increment_datapath_driver_rx_alloc_failures(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_driver_rx_alloc_failures++;
}

uint32_t umac_stats_get_datapath_driver_rx_alloc_failures(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_driver_rx_alloc_failures;
}

void umac_stats_clear_datapath_driver_rx_alloc_failures(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_driver_rx_alloc_failures = 0;
}

void umac_stats_increment_datapath_driver_rx_read_failures(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_driver_rx_read_failures++;
}

uint32_t umac_stats_get_datapath_driver_rx_read_failures(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_driver_rx_read_failures;
}

void umac_stats_clear_datapath_driver_rx_read_failures(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_driver_rx_read_failures = 0;
}

void umac_stats_update_datapath_rx_reorder_list_high_water_mark(struct umac_data *umacd,
                                                                uint8_t datapath_rx_reorder_list)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);
    if (datapath_rx_reorder_list > data->datapath_rx_reorder_list_high_water_mark)
    {
        data->datapath_rx_reorder_list_high_water_mark = datapath_rx_reorder_list;
    }
}

uint8_t umac_stats_get_datapath_rx_reorder_list_high_water_mark(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_rx_reorder_list_high_water_mark;
}

void umac_stats_clear_datapath_rx_reorder_list_high_water_mark(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_list_high_water_mark = 0;
}

void umac_stats_increment_datapath_rx_reorder_overflow(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_overflow++;
}

uint32_t umac_stats_get_datapath_rx_reorder_overflow(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_rx_reorder_overflow;
}

void umac_stats_clear_datapath_rx_reorder_overflow(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_overflow = 0;
}

void umac_stats_increment_datapath_rx_reorder_timedout(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_timedout++;
}

uint32_t umac_stats_get_datapath_rx_reorder_timedout(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_rx_reorder_timedout;
}

void umac_stats_clear_datapath_rx_reorder_timedout(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_timedout = 0;
}

void umac_stats_increment_datapath_rx_reorder_outdated_drops(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_outdated_drops++;
}

uint32_t umac_stats_get_datapath_rx_reorder_outdated_drops(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_rx_reorder_outdated_drops;
}

void umac_stats_clear_datapath_rx_reorder_outdated_drops(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_outdated_drops = 0;
}

void umac_stats_increment_datapath_rx_reorder_retransmit_drops(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_retransmit_drops++;
}

uint32_t umac_stats_get_datapath_rx_reorder_retransmit_drops(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_rx_reorder_retransmit_drops;
}

void umac_stats_clear_datapath_rx_reorder_retransmit_drops(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_retransmit_drops = 0;
}

void umac_stats_increment_datapath_rx_reorder_total(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_total++;
}

uint32_t umac_stats_get_datapath_rx_reorder_total(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_rx_reorder_total;
}

void umac_stats_clear_datapath_rx_reorder_total(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_rx_reorder_total = 0;
}

void umac_stats_increment_timeouts_fired(struct umac_data *umacd, uint32_t step)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->timeouts_fired += step;
}

uint32_t umac_stats_get_timeouts_fired(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->timeouts_fired;
}

void umac_stats_clear_timeouts_fired(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->timeouts_fired = 0;
}

void umac_stats_increment_datapath_driver_tx_skbq_timeout(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_driver_tx_skbq_timeout++;
}

uint32_t umac_stats_get_datapath_driver_tx_skbq_timeout(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_driver_tx_skbq_timeout;
}

void umac_stats_clear_datapath_driver_tx_skbq_timeout(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_driver_tx_skbq_timeout = 0;
}

void umac_stats_increment_datapath_driver_tx_pending_status_timeout(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_driver_tx_pending_status_timeout++;
}

uint32_t umac_stats_get_datapath_driver_tx_pending_status_timeout(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    return data->datapath_driver_tx_pending_status_timeout;
}

void umac_stats_clear_datapath_driver_tx_pending_status_timeout(struct umac_data *umacd)
{
    struct mmwlan_stats_umac_data *data = umac_data_get_stats(umacd);

    data->datapath_driver_tx_pending_status_timeout = 0;
}
