/*
 * Copyright 2022-2023 Morse Micro
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-MorseMicroCommercial
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */



#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


enum connection_mon_fsm_state
{
    CONNECTION_MON_FSM_STATE_NONE,
    CONNECTION_MON_FSM_STATE_DISABLED,
    CONNECTION_MON_FSM_STATE_STABLE,
    CONNECTION_MON_FSM_STATE_UNSTABLE,
    CONNECTION_MON_FSM_STATE_LOST,
};


enum connection_mon_fsm_state_mask
{
    CONNECTION_MON_FSM_STATE_DISABLED_MASK = (1ul << CONNECTION_MON_FSM_STATE_DISABLED),
    CONNECTION_MON_FSM_STATE_STABLE_MASK = (1ul << CONNECTION_MON_FSM_STATE_STABLE),
    CONNECTION_MON_FSM_STATE_UNSTABLE_MASK = (1ul << CONNECTION_MON_FSM_STATE_UNSTABLE),
    CONNECTION_MON_FSM_STATE_LOST_MASK = (1ul << CONNECTION_MON_FSM_STATE_LOST),
};


enum connection_mon_fsm_event
{
    CONNECTION_MON_FSM_EVENT_NONE,
    CONNECTION_MON_FSM_EVENT_START,
    CONNECTION_MON_FSM_EVENT_STOP,
    CONNECTION_MON_FSM_EVENT_BEACON_LOSS,
    CONNECTION_MON_FSM_EVENT_ACKED,
    CONNECTION_MON_FSM_EVENT_UNRESPONSIVE,
};


enum connection_mon_fsm_event_mask
{
    CONNECTION_MON_FSM_EVENT_START_MASK = (1ul << CONNECTION_MON_FSM_EVENT_START),
    CONNECTION_MON_FSM_EVENT_STOP_MASK = (1ul << CONNECTION_MON_FSM_EVENT_STOP),
    CONNECTION_MON_FSM_EVENT_BEACON_LOSS_MASK = (1ul << CONNECTION_MON_FSM_EVENT_BEACON_LOSS),
    CONNECTION_MON_FSM_EVENT_ACKED_MASK = (1ul << CONNECTION_MON_FSM_EVENT_ACKED),
    CONNECTION_MON_FSM_EVENT_UNRESPONSIVE_MASK = (1ul << CONNECTION_MON_FSM_EVENT_UNRESPONSIVE),
};


struct connection_mon_fsm_instance
{

    enum connection_mon_fsm_state current_state;

    volatile bool in_event_handler;

    enum connection_mon_fsm_event pending_event;

    void *arg;
};


#define CONNECTION_MON_FSM_INSTANCE_INIT                    \
    {                                                       \
        .current_state = CONNECTION_MON_FSM_STATE_DISABLED, \
        .in_event_handler = false,                          \
        .pending_event = CONNECTION_MON_FSM_EVENT_NONE,     \
        .arg = NULL,                                        \
    }


static inline void connection_mon_fsm_init(struct connection_mon_fsm_instance *inst)
{
    static const struct connection_mon_fsm_instance inst_init = CONNECTION_MON_FSM_INSTANCE_INIT;
    *inst = inst_init;
}


void connection_mon_fsm_handle_event(struct connection_mon_fsm_instance *inst,
                                     enum connection_mon_fsm_event event);


