/*
 * Copyright 2022-2023 Morse Micro
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-MorseMicroCommercial
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 *
 * Note: this file contains function definitions and therefore must only be included once from
 *       a single C source file.
 */
#include "connection_mon_fsm.h"

#define CONNECTION_MON_FSM_INITIAL_STATE CONNECTION_MON_FSM_STATE_DISABLED


#ifndef CONNECTION_MON_FSM_LOG
#define CONNECTION_MON_FSM_LOG(format_str, ...) \
    do {                                        \
        (void)format_str;                       \
    } while (0)
#endif


static void connection_mon_fsm_stable_entry(struct connection_mon_fsm_instance *inst,
                                            enum connection_mon_fsm_state prev_state);
static void connection_mon_fsm_unstable_entry(struct connection_mon_fsm_instance *inst,
                                              enum connection_mon_fsm_state prev_state);
static void connection_mon_fsm_unstable_exit(struct connection_mon_fsm_instance *inst,
                                             enum connection_mon_fsm_event event);
static void connection_mon_fsm_lost_entry(struct connection_mon_fsm_instance *inst,
                                          enum connection_mon_fsm_state prev_state);





static void connection_mon_fsm_transition_error(struct connection_mon_fsm_instance *inst,
                                                enum connection_mon_fsm_event event);

static void connection_mon_fsm_reentrance_error(struct connection_mon_fsm_instance *inst);



typedef void (*connection_mon_fsm_callback_t)(struct connection_mon_fsm_instance *inst,
                                              enum connection_mon_fsm_event event);

struct connection_mon_fsm_table_row
{
    uint32_t from_states;
    uint32_t events;
    enum connection_mon_fsm_state to_state;
    connection_mon_fsm_callback_t callback;
};

const struct connection_mon_fsm_table_row connection_mon_fsm_table[] = {
    {
        .from_states = CONNECTION_MON_FSM_STATE_LOST_MASK |
                       CONNECTION_MON_FSM_STATE_STABLE_MASK |
                       CONNECTION_MON_FSM_STATE_UNSTABLE_MASK,
        .events = CONNECTION_MON_FSM_EVENT_STOP_MASK,
        .to_state = CONNECTION_MON_FSM_STATE_DISABLED,
        .callback = NULL,
    },
    {
        .from_states = CONNECTION_MON_FSM_STATE_STABLE_MASK |
                       CONNECTION_MON_FSM_STATE_UNSTABLE_MASK,
        .events = CONNECTION_MON_FSM_EVENT_ACKED_MASK,
        .to_state = CONNECTION_MON_FSM_STATE_STABLE,
        .callback = NULL,
    },
    {
        .from_states = CONNECTION_MON_FSM_STATE_STABLE_MASK |
                       CONNECTION_MON_FSM_STATE_UNSTABLE_MASK,
        .events = CONNECTION_MON_FSM_EVENT_BEACON_LOSS_MASK,
        .to_state = CONNECTION_MON_FSM_STATE_UNSTABLE,
        .callback = NULL,
    },
    {
        .from_states = CONNECTION_MON_FSM_STATE_DISABLED_MASK,
        .events = CONNECTION_MON_FSM_EVENT_START_MASK,
        .to_state = CONNECTION_MON_FSM_STATE_STABLE,
        .callback = NULL,
    },
    {
        .from_states = CONNECTION_MON_FSM_STATE_UNSTABLE_MASK,
        .events = CONNECTION_MON_FSM_EVENT_UNRESPONSIVE_MASK,
        .to_state = CONNECTION_MON_FSM_STATE_LOST,
        .callback = NULL,
    },
};

#define CONNECTION_MON_FSM_TABLE_N_ENTRIES 5


static inline const char *connection_mon_fsm_state_tostr(enum connection_mon_fsm_state state)
{
    switch (state)
    {
        case 0:
            return "NONE";
        case CONNECTION_MON_FSM_STATE_DISABLED:
            return "disabled";
        case CONNECTION_MON_FSM_STATE_STABLE:
            return "stable";
        case CONNECTION_MON_FSM_STATE_UNSTABLE:
            return "unstable";
        case CONNECTION_MON_FSM_STATE_LOST:
            return "lost";
        default:
            return "??";
    }
}

static inline const char *connection_mon_fsm_event_tostr(enum connection_mon_fsm_event event)
{
    switch (event)
    {
        case 0:
            return "INVALID";
        case CONNECTION_MON_FSM_EVENT_START:
            return "start";
        case CONNECTION_MON_FSM_EVENT_STOP:
            return "stop";
        case CONNECTION_MON_FSM_EVENT_BEACON_LOSS:
            return "beacon_loss";
        case CONNECTION_MON_FSM_EVENT_ACKED:
            return "acked";
        case CONNECTION_MON_FSM_EVENT_UNRESPONSIVE:
            return "unresponsive";
        default:
            return "??";
    }
}

static void connection_mon_fsm_handle_event_internal(struct connection_mon_fsm_instance *inst,
                                                     enum connection_mon_fsm_event event)
{
    uint32_t ii;

    uint32_t current_state_mask = 1ul << inst->current_state;
    uint32_t event_mask = 1ul << event;

    for (ii = 0; ii < CONNECTION_MON_FSM_TABLE_N_ENTRIES; ii++)
    {
        const struct connection_mon_fsm_table_row *row = &connection_mon_fsm_table[ii];
        if ((row->from_states & current_state_mask) && (row->events & event_mask))
        {
            CONNECTION_MON_FSM_LOG("Event %s in state %s -> %s / %p\n",
                                   connection_mon_fsm_event_tostr(event),
                                   connection_mon_fsm_state_tostr(inst->current_state),
                                   connection_mon_fsm_state_tostr(row->to_state),
                                   row->callback);

            if (row->callback)
            {
                row->callback(inst, event);
            }
            if (row->to_state != CONNECTION_MON_FSM_STATE_NONE)
            {
                enum connection_mon_fsm_state prev_state = inst->current_state;
                switch (prev_state)
                {
                    case CONNECTION_MON_FSM_STATE_UNSTABLE:
                        connection_mon_fsm_unstable_exit(inst, event);
                        break;
                    default:
                        break;
                }

                inst->current_state = row->to_state;

                switch (inst->current_state)
                {
                    case CONNECTION_MON_FSM_STATE_STABLE:
                        connection_mon_fsm_stable_entry(inst, prev_state);
                        break;
                    case CONNECTION_MON_FSM_STATE_UNSTABLE:
                        connection_mon_fsm_unstable_entry(inst, prev_state);
                        break;
                    case CONNECTION_MON_FSM_STATE_LOST:
                        connection_mon_fsm_lost_entry(inst, prev_state);
                        break;
                    default:
                        break;
                }
            }
            return;
        }
    }
    connection_mon_fsm_transition_error(inst, event);
}


void connection_mon_fsm_handle_event(struct connection_mon_fsm_instance *inst,
                                     enum connection_mon_fsm_event event)
{
    if (inst->in_event_handler)
    {
        if (inst->pending_event != CONNECTION_MON_FSM_EVENT_NONE)
        {
            connection_mon_fsm_reentrance_error(inst);
        }
        else
        {
            inst->pending_event = event;
        }
        return;
    }

    inst->in_event_handler = true;

    while (event != CONNECTION_MON_FSM_EVENT_NONE)
    {
        connection_mon_fsm_handle_event_internal(inst, event);
        event = inst->pending_event;
        inst->pending_event = CONNECTION_MON_FSM_EVENT_NONE;
    }

    inst->in_event_handler = false;
}
