/*
 * Copyright 2022-2023 Morse Micro
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-MorseMicroCommercial
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */



#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


enum connection_fsm_state
{
    CONNECTION_FSM_STATE_NONE,
    CONNECTION_FSM_STATE_DISABLED,
    CONNECTION_FSM_STATE_DISCONNECTED,
    CONNECTION_FSM_STATE_AUTHENTICATING,
    CONNECTION_FSM_STATE_CONNECTING,
    CONNECTION_FSM_STATE_CONNECTED,
};


enum connection_fsm_state_mask
{
    CONNECTION_FSM_STATE_DISABLED_MASK = (1ul << CONNECTION_FSM_STATE_DISABLED),
    CONNECTION_FSM_STATE_DISCONNECTED_MASK = (1ul << CONNECTION_FSM_STATE_DISCONNECTED),
    CONNECTION_FSM_STATE_AUTHENTICATING_MASK = (1ul << CONNECTION_FSM_STATE_AUTHENTICATING),
    CONNECTION_FSM_STATE_CONNECTING_MASK = (1ul << CONNECTION_FSM_STATE_CONNECTING),
    CONNECTION_FSM_STATE_CONNECTED_MASK = (1ul << CONNECTION_FSM_STATE_CONNECTED),
};


enum connection_fsm_event
{
    CONNECTION_FSM_EVENT_NONE,
    CONNECTION_FSM_EVENT_SUPP_PORT_OPEN,
    CONNECTION_FSM_EVENT_AUTH_REQUEST,
    CONNECTION_FSM_EVENT_ASSOC_REQUEST,
    CONNECTION_FSM_EVENT_DISCONNECT,
};


enum connection_fsm_event_mask
{
    CONNECTION_FSM_EVENT_SUPP_PORT_OPEN_MASK = (1ul << CONNECTION_FSM_EVENT_SUPP_PORT_OPEN),
    CONNECTION_FSM_EVENT_AUTH_REQUEST_MASK = (1ul << CONNECTION_FSM_EVENT_AUTH_REQUEST),
    CONNECTION_FSM_EVENT_ASSOC_REQUEST_MASK = (1ul << CONNECTION_FSM_EVENT_ASSOC_REQUEST),
    CONNECTION_FSM_EVENT_DISCONNECT_MASK = (1ul << CONNECTION_FSM_EVENT_DISCONNECT),
};


struct connection_fsm_instance
{

    enum connection_fsm_state current_state;

    volatile bool in_event_handler;

    enum connection_fsm_event pending_event;

    void *arg;
};


#define CONNECTION_FSM_INSTANCE_INIT                    \
    {                                                   \
        .current_state = CONNECTION_FSM_STATE_DISABLED, \
        .in_event_handler = false,                      \
        .pending_event = CONNECTION_FSM_EVENT_NONE,     \
        .arg = NULL,                                    \
    }


static inline void connection_fsm_init(struct connection_fsm_instance *inst)
{
    static const struct connection_fsm_instance inst_init = CONNECTION_FSM_INSTANCE_INIT;
    *inst = inst_init;
}


void connection_fsm_handle_event(struct connection_fsm_instance *inst,
                                 enum connection_fsm_event event);


