/*
 * Copyright 2022-2023 Morse Micro
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-MorseMicroCommercial
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 *
 * Note: this file contains function definitions and therefore must only be included once from
 *       a single C source file.
 */
#include "connection_fsm.h"

#define CONNECTION_FSM_INITIAL_STATE CONNECTION_FSM_STATE_DISABLED


#ifndef CONNECTION_FSM_LOG
#define CONNECTION_FSM_LOG(format_str, ...) \
    do {                                    \
        (void)format_str;                   \
    } while (0)
#endif


static void connection_fsm_disconnected_entry(struct connection_fsm_instance *inst,
                                              enum connection_fsm_state prev_state);
static void connection_fsm_disconnected_exit(struct connection_fsm_instance *inst,
                                             enum connection_fsm_event event);
static void connection_fsm_authenticating_entry(struct connection_fsm_instance *inst,
                                                enum connection_fsm_state prev_state);
static void connection_fsm_connecting_entry(struct connection_fsm_instance *inst,
                                            enum connection_fsm_state prev_state);
static void connection_fsm_connected_entry(struct connection_fsm_instance *inst,
                                           enum connection_fsm_state prev_state);
static void connection_fsm_connected_exit(struct connection_fsm_instance *inst,
                                          enum connection_fsm_event event);





static void connection_fsm_transition_error(struct connection_fsm_instance *inst,
                                            enum connection_fsm_event event);

static void connection_fsm_reentrance_error(struct connection_fsm_instance *inst);



typedef void (*connection_fsm_callback_t)(struct connection_fsm_instance *inst,
                                          enum connection_fsm_event event);

struct connection_fsm_table_row
{
    uint32_t from_states;
    uint32_t events;
    enum connection_fsm_state to_state;
    connection_fsm_callback_t callback;
};

const struct connection_fsm_table_row connection_fsm_table[] = {
    {
        .from_states = CONNECTION_FSM_STATE_AUTHENTICATING_MASK |
                       CONNECTION_FSM_STATE_CONNECTED_MASK |
                       CONNECTION_FSM_STATE_CONNECTING_MASK |
                       CONNECTION_FSM_STATE_DISABLED_MASK |
                       CONNECTION_FSM_STATE_DISCONNECTED_MASK,
        .events = CONNECTION_FSM_EVENT_DISCONNECT_MASK,
        .to_state = CONNECTION_FSM_STATE_DISCONNECTED,
        .callback = NULL,
    },
    {
        .from_states = CONNECTION_FSM_STATE_AUTHENTICATING_MASK |
                       CONNECTION_FSM_STATE_CONNECTING_MASK |
                       CONNECTION_FSM_STATE_DISCONNECTED_MASK,
        .events = CONNECTION_FSM_EVENT_AUTH_REQUEST_MASK,
        .to_state = CONNECTION_FSM_STATE_AUTHENTICATING,
        .callback = NULL,
    },
    {
        .from_states = CONNECTION_FSM_STATE_AUTHENTICATING_MASK,
        .events = CONNECTION_FSM_EVENT_ASSOC_REQUEST_MASK,
        .to_state = CONNECTION_FSM_STATE_CONNECTING,
        .callback = NULL,
    },
    {
        .from_states = CONNECTION_FSM_STATE_CONNECTING_MASK,
        .events = CONNECTION_FSM_EVENT_SUPP_PORT_OPEN_MASK,
        .to_state = CONNECTION_FSM_STATE_CONNECTED,
        .callback = NULL,
    },
};

#define CONNECTION_FSM_TABLE_N_ENTRIES 4


static inline const char *connection_fsm_state_tostr(enum connection_fsm_state state)
{
    switch (state)
    {
        case 0:
            return "NONE";
        case CONNECTION_FSM_STATE_DISABLED:
            return "disabled";
        case CONNECTION_FSM_STATE_DISCONNECTED:
            return "disconnected";
        case CONNECTION_FSM_STATE_AUTHENTICATING:
            return "authenticating";
        case CONNECTION_FSM_STATE_CONNECTING:
            return "connecting";
        case CONNECTION_FSM_STATE_CONNECTED:
            return "connected";
        default:
            return "??";
    }
}

static inline const char *connection_fsm_event_tostr(enum connection_fsm_event event)
{
    switch (event)
    {
        case 0:
            return "INVALID";
        case CONNECTION_FSM_EVENT_SUPP_PORT_OPEN:
            return "supp_port_open";
        case CONNECTION_FSM_EVENT_AUTH_REQUEST:
            return "auth_request";
        case CONNECTION_FSM_EVENT_ASSOC_REQUEST:
            return "assoc_request";
        case CONNECTION_FSM_EVENT_DISCONNECT:
            return "disconnect";
        default:
            return "??";
    }
}

static void connection_fsm_handle_event_internal(struct connection_fsm_instance *inst,
                                                 enum connection_fsm_event event)
{
    uint32_t ii;

    uint32_t current_state_mask = 1ul << inst->current_state;
    uint32_t event_mask = 1ul << event;

    for (ii = 0; ii < CONNECTION_FSM_TABLE_N_ENTRIES; ii++)
    {
        const struct connection_fsm_table_row *row = &connection_fsm_table[ii];
        if ((row->from_states & current_state_mask) && (row->events & event_mask))
        {
            CONNECTION_FSM_LOG("Event %s in state %s -> %s / %p\n",
                               connection_fsm_event_tostr(event),
                               connection_fsm_state_tostr(inst->current_state),
                               connection_fsm_state_tostr(row->to_state),
                               row->callback);

            if (row->callback)
            {
                row->callback(inst, event);
            }
            if (row->to_state != CONNECTION_FSM_STATE_NONE)
            {
                enum connection_fsm_state prev_state = inst->current_state;
                switch (prev_state)
                {
                    case CONNECTION_FSM_STATE_DISCONNECTED:
                        connection_fsm_disconnected_exit(inst, event);
                        break;
                    case CONNECTION_FSM_STATE_CONNECTED:
                        connection_fsm_connected_exit(inst, event);
                        break;
                    default:
                        break;
                }

                inst->current_state = row->to_state;

                switch (inst->current_state)
                {
                    case CONNECTION_FSM_STATE_DISCONNECTED:
                        connection_fsm_disconnected_entry(inst, prev_state);
                        break;
                    case CONNECTION_FSM_STATE_AUTHENTICATING:
                        connection_fsm_authenticating_entry(inst, prev_state);
                        break;
                    case CONNECTION_FSM_STATE_CONNECTING:
                        connection_fsm_connecting_entry(inst, prev_state);
                        break;
                    case CONNECTION_FSM_STATE_CONNECTED:
                        connection_fsm_connected_entry(inst, prev_state);
                        break;
                    default:
                        break;
                }
            }
            return;
        }
    }
    connection_fsm_transition_error(inst, event);
}


void connection_fsm_handle_event(struct connection_fsm_instance *inst,
                                 enum connection_fsm_event event)
{
    if (inst->in_event_handler)
    {
        if (inst->pending_event != CONNECTION_FSM_EVENT_NONE)
        {
            connection_fsm_reentrance_error(inst);
        }
        else
        {
            inst->pending_event = event;
        }
        return;
    }

    inst->in_event_handler = true;

    while (event != CONNECTION_FSM_EVENT_NONE)
    {
        connection_fsm_handle_event_internal(inst, event);
        event = inst->pending_event;
        inst->pending_event = CONNECTION_FSM_EVENT_NONE;
    }

    inst->in_event_handler = false;
}
