/*
 * Copyright 2023 Morse Micro
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-MorseMicroCommercial
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */



#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


enum wnm_sleep_fsm_state
{
    WNM_SLEEP_FSM_STATE_NONE,
    WNM_SLEEP_FSM_STATE_IDLE,
    WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED,
    WNM_SLEEP_FSM_STATE_ACTIVE,
    WNM_SLEEP_FSM_STATE_EXIT_REQUESTED,
};


enum wnm_sleep_fsm_state_mask
{
    WNM_SLEEP_FSM_STATE_IDLE_MASK = (1ul << WNM_SLEEP_FSM_STATE_IDLE),
    WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED_MASK = (1ul << WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED),
    WNM_SLEEP_FSM_STATE_ACTIVE_MASK = (1ul << WNM_SLEEP_FSM_STATE_ACTIVE),
    WNM_SLEEP_FSM_STATE_EXIT_REQUESTED_MASK = (1ul << WNM_SLEEP_FSM_STATE_EXIT_REQUESTED),
};


enum wnm_sleep_fsm_event
{
    WNM_SLEEP_FSM_EVENT_NONE,
    WNM_SLEEP_FSM_EVENT_ENABLE,
    WNM_SLEEP_FSM_EVENT_DISABLE,
    WNM_SLEEP_FSM_EVENT_CONNECTION_LOST,
    WNM_SLEEP_FSM_EVENT_ENTRY_CONFIRMED,
    WNM_SLEEP_FSM_EVENT_EXIT_CONFIRMED,
    WNM_SLEEP_FSM_EVENT_RETRY_REQUEST,
    WNM_SLEEP_FSM_EVENT_RETRIES_EXHAUSTED,
};


enum wnm_sleep_fsm_event_mask
{
    WNM_SLEEP_FSM_EVENT_ENABLE_MASK = (1ul << WNM_SLEEP_FSM_EVENT_ENABLE),
    WNM_SLEEP_FSM_EVENT_DISABLE_MASK = (1ul << WNM_SLEEP_FSM_EVENT_DISABLE),
    WNM_SLEEP_FSM_EVENT_CONNECTION_LOST_MASK = (1ul << WNM_SLEEP_FSM_EVENT_CONNECTION_LOST),
    WNM_SLEEP_FSM_EVENT_ENTRY_CONFIRMED_MASK = (1ul << WNM_SLEEP_FSM_EVENT_ENTRY_CONFIRMED),
    WNM_SLEEP_FSM_EVENT_EXIT_CONFIRMED_MASK = (1ul << WNM_SLEEP_FSM_EVENT_EXIT_CONFIRMED),
    WNM_SLEEP_FSM_EVENT_RETRY_REQUEST_MASK = (1ul << WNM_SLEEP_FSM_EVENT_RETRY_REQUEST),
    WNM_SLEEP_FSM_EVENT_RETRIES_EXHAUSTED_MASK = (1ul << WNM_SLEEP_FSM_EVENT_RETRIES_EXHAUSTED),
};


struct wnm_sleep_fsm_instance
{

    enum wnm_sleep_fsm_state current_state;

    volatile bool in_event_handler;

    enum wnm_sleep_fsm_event pending_event;

    void *arg;
};


#define WNM_SLEEP_FSM_INSTANCE_INIT                \
    {                                              \
        .current_state = WNM_SLEEP_FSM_STATE_IDLE, \
        .in_event_handler = false,                 \
        .pending_event = WNM_SLEEP_FSM_EVENT_NONE, \
        .arg = NULL,                               \
    }


static inline void wnm_sleep_fsm_init(struct wnm_sleep_fsm_instance *inst)
{
    static const struct wnm_sleep_fsm_instance inst_init = WNM_SLEEP_FSM_INSTANCE_INIT;
    *inst = inst_init;
}


void wnm_sleep_fsm_handle_event(struct wnm_sleep_fsm_instance *inst,
                                enum wnm_sleep_fsm_event event);


