/*
 * Copyright 2023 Morse Micro
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-MorseMicroCommercial
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 *
 * Note: this file contains function definitions and therefore must only be included once from
 *       a single C source file.
 */
#include "wnm_sleep_fsm.h"

#define WNM_SLEEP_FSM_INITIAL_STATE WNM_SLEEP_FSM_STATE_IDLE


#ifndef WNM_SLEEP_FSM_LOG
#define WNM_SLEEP_FSM_LOG(format_str, ...) \
    do {                                   \
        (void)format_str;                  \
    } while (0)
#endif


static void wnm_sleep_fsm_entry_requested_entry(struct wnm_sleep_fsm_instance *inst,
                                                enum wnm_sleep_fsm_state prev_state);
static void wnm_sleep_fsm_entry_requested_exit(struct wnm_sleep_fsm_instance *inst,
                                               enum wnm_sleep_fsm_event event);
static void wnm_sleep_fsm_active_entry(struct wnm_sleep_fsm_instance *inst,
                                       enum wnm_sleep_fsm_state prev_state);
static void wnm_sleep_fsm_active_exit(struct wnm_sleep_fsm_instance *inst,
                                      enum wnm_sleep_fsm_event event);
static void wnm_sleep_fsm_exit_requested_entry(struct wnm_sleep_fsm_instance *inst,
                                               enum wnm_sleep_fsm_state prev_state);
static void wnm_sleep_fsm_exit_requested_exit(struct wnm_sleep_fsm_instance *inst,
                                              enum wnm_sleep_fsm_event event);





static void wnm_sleep_fsm_transition_error(struct wnm_sleep_fsm_instance *inst,
                                           enum wnm_sleep_fsm_event event);

static void wnm_sleep_fsm_reentrance_error(struct wnm_sleep_fsm_instance *inst);



typedef void (*wnm_sleep_fsm_callback_t)(struct wnm_sleep_fsm_instance *inst,
                                         enum wnm_sleep_fsm_event event);

struct wnm_sleep_fsm_table_row
{
    uint32_t from_states;
    uint32_t events;
    enum wnm_sleep_fsm_state to_state;
    wnm_sleep_fsm_callback_t callback;
};

const struct wnm_sleep_fsm_table_row wnm_sleep_fsm_table[] = {
    {
        .from_states = WNM_SLEEP_FSM_STATE_EXIT_REQUESTED_MASK,
        .events = WNM_SLEEP_FSM_EVENT_CONNECTION_LOST_MASK |
                  WNM_SLEEP_FSM_EVENT_EXIT_CONFIRMED_MASK |
                  WNM_SLEEP_FSM_EVENT_RETRIES_EXHAUSTED_MASK,
        .to_state = WNM_SLEEP_FSM_STATE_IDLE,
        .callback = NULL,
    },
    {
        .from_states = WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED_MASK,
        .events = WNM_SLEEP_FSM_EVENT_CONNECTION_LOST_MASK |
                  WNM_SLEEP_FSM_EVENT_RETRIES_EXHAUSTED_MASK,
        .to_state = WNM_SLEEP_FSM_STATE_IDLE,
        .callback = NULL,
    },
    {
        .from_states = WNM_SLEEP_FSM_STATE_EXIT_REQUESTED_MASK | WNM_SLEEP_FSM_STATE_IDLE_MASK,
        .events = WNM_SLEEP_FSM_EVENT_ENABLE_MASK,
        .to_state = WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED,
        .callback = NULL,
    },
    {
        .from_states = WNM_SLEEP_FSM_STATE_ACTIVE_MASK | WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED_MASK,
        .events = WNM_SLEEP_FSM_EVENT_DISABLE_MASK,
        .to_state = WNM_SLEEP_FSM_STATE_EXIT_REQUESTED,
        .callback = NULL,
    },
    {
        .from_states = WNM_SLEEP_FSM_STATE_ACTIVE_MASK,
        .events = WNM_SLEEP_FSM_EVENT_CONNECTION_LOST_MASK,
        .to_state = WNM_SLEEP_FSM_STATE_IDLE,
        .callback = NULL,
    },
    {
        .from_states = WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED_MASK,
        .events = WNM_SLEEP_FSM_EVENT_ENTRY_CONFIRMED_MASK,
        .to_state = WNM_SLEEP_FSM_STATE_ACTIVE,
        .callback = NULL,
    },
    {
        .from_states = WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED_MASK,
        .events = WNM_SLEEP_FSM_EVENT_RETRY_REQUEST_MASK,
        .to_state = WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED,
        .callback = NULL,
    },
    {
        .from_states = WNM_SLEEP_FSM_STATE_EXIT_REQUESTED_MASK,
        .events = WNM_SLEEP_FSM_EVENT_RETRY_REQUEST_MASK,
        .to_state = WNM_SLEEP_FSM_STATE_EXIT_REQUESTED,
        .callback = NULL,
    },
};

#define WNM_SLEEP_FSM_TABLE_N_ENTRIES 8


static inline const char *wnm_sleep_fsm_state_tostr(enum wnm_sleep_fsm_state state)
{
    switch (state)
    {
        case 0:
            return "NONE";
        case WNM_SLEEP_FSM_STATE_IDLE:
            return "idle";
        case WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED:
            return "entry_requested";
        case WNM_SLEEP_FSM_STATE_ACTIVE:
            return "active";
        case WNM_SLEEP_FSM_STATE_EXIT_REQUESTED:
            return "exit_requested";
        default:
            return "??";
    }
}

static inline const char *wnm_sleep_fsm_event_tostr(enum wnm_sleep_fsm_event event)
{
    switch (event)
    {
        case 0:
            return "INVALID";
        case WNM_SLEEP_FSM_EVENT_ENABLE:
            return "enable";
        case WNM_SLEEP_FSM_EVENT_DISABLE:
            return "disable";
        case WNM_SLEEP_FSM_EVENT_CONNECTION_LOST:
            return "connection_lost";
        case WNM_SLEEP_FSM_EVENT_ENTRY_CONFIRMED:
            return "entry_confirmed";
        case WNM_SLEEP_FSM_EVENT_EXIT_CONFIRMED:
            return "exit_confirmed";
        case WNM_SLEEP_FSM_EVENT_RETRY_REQUEST:
            return "retry_request";
        case WNM_SLEEP_FSM_EVENT_RETRIES_EXHAUSTED:
            return "retries_exhausted";
        default:
            return "??";
    }
}

static void wnm_sleep_fsm_handle_event_internal(struct wnm_sleep_fsm_instance *inst,
                                                enum wnm_sleep_fsm_event event)
{
    uint32_t ii;

    uint32_t current_state_mask = 1ul << inst->current_state;
    uint32_t event_mask = 1ul << event;

    for (ii = 0; ii < WNM_SLEEP_FSM_TABLE_N_ENTRIES; ii++)
    {
        const struct wnm_sleep_fsm_table_row *row = &wnm_sleep_fsm_table[ii];
        if ((row->from_states & current_state_mask) && (row->events & event_mask))
        {
            WNM_SLEEP_FSM_LOG("Event %s in state %s -> %s / %p\n",
                              wnm_sleep_fsm_event_tostr(event),
                              wnm_sleep_fsm_state_tostr(inst->current_state),
                              wnm_sleep_fsm_state_tostr(row->to_state),
                              row->callback);

            if (row->callback)
            {
                row->callback(inst, event);
            }
            if (row->to_state != WNM_SLEEP_FSM_STATE_NONE)
            {
                enum wnm_sleep_fsm_state prev_state = inst->current_state;
                switch (prev_state)
                {
                    case WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED:
                        wnm_sleep_fsm_entry_requested_exit(inst, event);
                        break;
                    case WNM_SLEEP_FSM_STATE_ACTIVE:
                        wnm_sleep_fsm_active_exit(inst, event);
                        break;
                    case WNM_SLEEP_FSM_STATE_EXIT_REQUESTED:
                        wnm_sleep_fsm_exit_requested_exit(inst, event);
                        break;
                    default:
                        break;
                }

                inst->current_state = row->to_state;

                switch (inst->current_state)
                {
                    case WNM_SLEEP_FSM_STATE_ENTRY_REQUESTED:
                        wnm_sleep_fsm_entry_requested_entry(inst, prev_state);
                        break;
                    case WNM_SLEEP_FSM_STATE_ACTIVE:
                        wnm_sleep_fsm_active_entry(inst, prev_state);
                        break;
                    case WNM_SLEEP_FSM_STATE_EXIT_REQUESTED:
                        wnm_sleep_fsm_exit_requested_entry(inst, prev_state);
                        break;
                    default:
                        break;
                }
            }
            return;
        }
    }
    wnm_sleep_fsm_transition_error(inst, event);
}


void wnm_sleep_fsm_handle_event(struct wnm_sleep_fsm_instance *inst, enum wnm_sleep_fsm_event event)
{
    if (inst->in_event_handler)
    {
        if (inst->pending_event != WNM_SLEEP_FSM_EVENT_NONE)
        {
            wnm_sleep_fsm_reentrance_error(inst);
        }
        else
        {
            inst->pending_event = event;
        }
        return;
    }

    inst->in_event_handler = true;

    while (event != WNM_SLEEP_FSM_EVENT_NONE)
    {
        wnm_sleep_fsm_handle_event_internal(inst, event);
        event = inst->pending_event;
        inst->pending_event = WNM_SLEEP_FSM_EVENT_NONE;
    }

    inst->in_event_handler = false;
}
