/**
 ******************************************************************************
 * @file    isp_param_conf.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2025-11-03 17:38:02
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for VD1943 sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_VD1943 = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 0,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 2,
        .BLCG = 2,
        .BLCB = 2,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_GBRG,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = { "MiniLBox A", "MiniLBox TL84", "MiniLBox D65", "Free Slot", "", },
        .referenceColorTemp = { 2665, 3750, 6140, 0, 0, },
        .ispGainR = { 107000000, 140000000, 199000000, 0, 0, },
        .ispGainG = { 100000000, 100000000, 100000000, 0, 0, },
        .ispGainB = { 351000000, 231999999, 174000000, 0, 0, },
        .coeff = {
            { { 153020000, -2980000, -50039999, }, { -58180000, 164940000, -6759999, }, { -2860000, -114470000, 217329998, }, },
            { { 168720000, -36410000, -32320000, }, { -41460000, 151940000, -10470000, }, { -300000, -81710000, 182010000, }, },
            { { 165130000, -37380000, -27750000, }, { -36710000, 153590000, -16880000, }, { -5990000, -51259999, 157250000, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
        },
        .referenceRGB = {
            { 62, 56, 16},
            { 56, 65, 26},
            { 43, 71, 38},
            { 0, 0, 0},
            { 0, 0, 0},
        },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 100,
        .Y0 = 100,
        .XSize = 2360,
        .YSize = 1784,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 4,
    },
    .luxRef = {
        .HL_LuxRef = 1090,
        .HL_Expo1 = 2457,
        .HL_Lum1 = 29,
        .HL_Expo2 = 8857,
        .HL_Lum2 = 101,
        .LL_LuxRef = 234,
        .LL_Expo1 = 10456,
        .LL_Lum1 = 29,
        .LL_Expo2 = 24028,
        .LL_Lum2 = 66,
        .calibFactor = 0.982f,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_VD1943
};

#endif /* __ISP_PARAM_CONF__H */
