/**
 ******************************************************************************
 * @file    isp_param_conf.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2025-12-08 18:18:28
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for VD1943 sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_VD1943 = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 0,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 2,
        .BLCG = 2,
        .BLCB = 2,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_GBRG,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = { "JudgeII-A", "JudgeII-TL84", "JudgeII-DAY", "", "", },
        .referenceColorTemp = { 2810, 4015, 6650, 0, 0, },
        .ispGainR = { 100000000, 129000000, 169000000, 0, 0, },
        .ispGainG = { 110000000, 100000000, 100000000, 0, 0, },
        .ispGainB = { 313000000, 218000000, 149000000, 0, 0, },
        .coeff = {
            { { 128099999, 68470000, -96580000, }, { -45100000, 158710000, -13610000, }, { -24710000, -106030000, 230740000, }, },
            { { 137580000, -4290000, -33289998, }, { -39140000, 147480000, -8340000, }, { -4730000, -58500000, 163230000, }, },
            { { 131870000, 12850000, -44730000, }, { -27980000, 168410000, -40420000, }, { -4500000, -45190000, 149690000, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
        },
        .referenceRGB = {
            { 68, 51, 18},
            { 54, 59, 24},
            { 42, 58, 36},
            { 0, 0, 0},
            { 0, 0, 0},
        },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 512,
        .Y0 = 396,
        .XSize = 1536,
        .YSize = 1190,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 4,
    },
    .luxRef = {
        .HL_LuxRef = 1090,
        .HL_Expo1 = 2457,
        .HL_Lum1 = 29,
        .HL_Expo2 = 8857,
        .HL_Lum2 = 101,
        .LL_LuxRef = 234,
        .LL_Expo1 = 10456,
        .LL_Lum1 = 29,
        .LL_Expo2 = 24028,
        .LL_Lum2 = 66,
        .calibFactor = 0.982f,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_VD1943
};

#endif /* __ISP_PARAM_CONF__H */
