/**
 ******************************************************************************
 * @file    isp_param_conf.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2025-12-12 12:14:29
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for VD65G4 sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_VD65G4 = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 0,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 2,
        .BLCG = 2,
        .BLCB = 2,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_RGGB,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = { "JudgeII-A", "JudgeII-TL84", "JudgeII-DAY", },
        .referenceColorTemp = { 2810, 4015, 6650, },
        .ispGainR = { 100000000, 125000000, 163000000, },
        .ispGainG = { 118000000, 100000000, 100000000, },
        .ispGainB = { 353000000, 229999999, 154000000, },
        .coeff = {
            { { 141770000, 20520000, -62280000, }, { -34860000, 160340000, -25480000, }, { -2410000, -117900000, 220299999, }, },
            { { 159340000, -18510000, -40840000, }, { -31110000, 151640000, -20530000, }, { 540000, -60850000, 160300000, }, },
            { { 150690000, -11530000, -39160000, }, { -20310000, 160490000, -40180000, }, { 2750000, -63910000, 161160000, }, },
        },
        .referenceRGB = {
            { 65, 46, 16},
            { 53, 56, 23},
            { 42, 55, 34},
        },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 160,
        .Y0 = 140,
        .XSize = 482,
        .YSize = 422,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 6,
    },
    .luxRef = {
        .HL_LuxRef = 1090,
        .HL_Expo1 = 4058,
        .HL_Lum1 = 33,
        .HL_Expo2 = 12858,
        .HL_Lum2 = 103,
        .LL_LuxRef = 234,
        .LL_Expo1 = 14784,
        .LL_Lum1 = 28,
        .LL_Expo2 = 34062,
        .LL_Lum2 = 65,
        .calibFactor = 0.999f,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_VD65G4
};

#endif /* __ISP_PARAM_CONF__H */
