/**
 ******************************************************************************
 * @file    isp_param_conf.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2025-04-03 11:17:27
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for VD66GY sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_VD66GY = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 0,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 16,
        .BLCG = 16,
        .BLCB = 16,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_GRBG,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = { "MiniLBox A", "MiniLBox TL84", "MiniLBox D65", "", "", },
        .referenceColorTemp = { 2665, 3750, 6140, 0, 0, },
        .ispGainR = { 100000000, 119000000, 167000000, 0, 0, },
        .ispGainG = { 111000000, 100000000, 100000000, 0, 0, },
        .ispGainB = { 369000000, 225000000, 172000000, 0, 0, },
        .coeff = {
            { { 148550000, -7320000, -41230000, }, { -59219999, 152400000, 6830000, }, { -1030000, -135090000, 236120000, }, },
            { { 157380000, -21290000, -36090000, }, { -46710000, 157140000, -10430000, }, { 50000, -85380000, 185340000, }, },
            { { 176220000, -48360000, -27860000, }, { -40050000, 158080000, -18020000, }, { -5650000, -61180000, 166820000, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
        },
        .referenceRGB = {
            { 80, 65, 30 },
            { 69, 70, 38 },
            { 54, 70, 45 },
            { 0, 0, 0 },
            { 0, 0, 0 },
        },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 140,
        .Y0 = 341,
        .XSize = 840,
        .YSize = 682,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 4,
    },
    .luxRef = {
        .HL_LuxRef = 1400,
        .HL_Expo1 = 2000,
        .HL_Lum1 = 42,
        .HL_Expo2 = 20000,
        .HL_Lum2 = 200,
        .LL_LuxRef = 300,
        .LL_Expo1 = 5000,
        .LL_Lum1 = 20,
        .LL_Expo2 = 29827,
        .LL_Lum2 = 111,
        .calibFactor = 0.738f,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_VD66GY
};

#endif /* __ISP_PARAM_CONF__H */
