/**
 ******************************************************************************
 * @file    vd66gy_mai1_isp_param_conf.h
 * @author  IMG Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 * This file must be copied into the application folder.
 * This file can be:
 * - either generated by the IQTT_generate_h.py script
 * - either manually updated by setting the IQ parameter values
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2025-05-06 13:07:57
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for VD66GY sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_VD66GY = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 0,
    },
    .AECAlgo = {
        .enable = 0,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 16,
        .BLCG = 16,
        .BLCB = 16,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_GRBG,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
     },
    .AWBAlgo = {
        .enable = 1,
        .id = { "U30", "INCA", "TL84", "D65", "Free Slot", },
        .referenceColorTemp = { 2500, 2850, 4000, 6500, 0, },
        .ispGainR = { 100000000, 100000000, 120000000, 171000000, 0, },
        .ispGainG = { 106000000, 109000000, 100000000, 100000000, 0, },
        .ispGainB = { 336000000, 323000000, 231000000, 151000000, 0, },
        .coeff = {
            { { 166570000, -19420000, -47150000, }, { -46460000, 163750000, -17290000, }, { 6090000, -139800000, 233710000, }, },
            { { 122640000, 39920000, -62560000, }, { -50249999, 173120000, -22870000, }, { -10420000, -95850000, 206270000, }, },
            { { 160390000, -20180000, -40210000, }, { -40380000, 164900000, -24520000, }, { 2280000, -84670000, 182390000, }, },
            { { 141380000, 11340000, -52710000, }, { -34510000, 185150000, -50639999, }, { -8890000, -39800000, 148690000, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
        },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 50,
        .Y0 = 50,
        .XSize = 1020,
        .YSize = 1264,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 4,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_VD66GY
};

#endif /* __ISP_PARAM_CONF__H */
