#!/usr/bin/env python3
"""Emit mmhal_wlan_binaries.c for the mm-iot-sdk 2.13.1 port.

Firmware arrays come from the 2.13.1 release mbins; the BCF selection and
read-callback logic is replicated verbatim from the 2.10.4 shim so runtime
behavior (chip switch + per-country BCF) is unchanged.

Usage:
  python gen_binaries_2_13_1.py [mm8108_fw_mbin] [mm8108_bcf_mbin]

The optional arguments override the embedded mm8108 firmware (default: the
official 2.13.1 mm8108b2-rl.mbin) and the mm8108 BCF (default: the Quectel
FGH200 v12 BCF). Overrides used so far:

- Interim build (v4.3.1.49, retired): legacy 2.10.4 vendor firmware. The 2.13.1
  mm8108 firmware requires BCF board-config format v13, and the only Quectel
  FGH200 BCF available (from the 2.10.4 vendor package) is v12 — the 2.13.1
  firmware rejects it (boot code 5) and enters failsafe mode, which mmdrv_init
  refuses. The legacy firmware accepts the v12 BCF, but the 2.13.1 host's
  morse_firmware_check_compatibility() requires chip major == 57, and the
  legacy firmware reports 56.17.0, so that combination cannot init either.

- Official-BCF build (v4.3.1.50+): bcf_mf15457_official_v13.mbin. The FGH200
  BCF's own board_desc says it is a modified copy of the mm8108-mf15457 module
  BCF, so the official v13 mf15457 BCF is the same module design's certified
  upstream build. Used until Quectel ships a v13 FGH200 BCF. Caveat: regdoms
  are AU/CA/EU/GB/JP/US only (no IN/KR/NZ entries, unlike the FGH200 copy).
"""
import re
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

MM8108_FW = sys.argv[1] if len(sys.argv) > 1 else "mm8108b2-rl.mbin"
MM8108_BCF = sys.argv[2] if len(sys.argv) > 2 else "bcf_bin/bcf_FGH200MAAMD.mbin"


def symbol_for(path):
    """bcf_bin/bcf_foo.mbin -> bcf_foo_mbin"""
    return re.sub(r"[^0-9a-zA-Z]", "_", path.rsplit("/", 1)[-1].rsplit(".", 1)[0]) + "_mbin"


MM8108_BCF_SYMBOL = symbol_for(MM8108_BCF)
INTERIM = "legacy" in MM8108_FW

HDR = """/*
 * NE301 HaLow firmware/BCF embedding for mm-iot-sdk 2.13.1.
 * Generated by gen_binaries_2_13_1.py - do not edit by hand.
 * Logic section mirrors mmx108/mm_shims/mmhal_wlan_binaries.c (2.10.4).
 * mm8108 firmware source: {fw_src}
 * mm8108 BCF source: {bcf_src}{interim_note}
 */

#include "mmhal_wlan.h"
#include "mmosal.h"
"""

INTERIM_NOTE = """
 *
 * INTERIM BUILD: the embedded mm8108 firmware is the 2.10.4 vendor build
 * (mm8108b2-rl-legacy.mbin), NOT the 2.13.1 release firmware. Reason: the
 * 2.13.1 mm8108 firmware requires BCF board-config v13; the only available
 * FGH200 BCF is v12 (rejected -> failsafe -> mmdrv_init assert loop).
 * Replace with the official firmware once a v13 FGH200 BCF is available.
"""

BCF_LOGIC = """
#ifdef HALOW_CHIP_MM8108
static const uint8_t *halow_bcf_selected_data = @MM8108_BCF@;
static size_t halow_bcf_selected_len = @MM8108_BCF_LEN@;
#else
static const uint8_t *halow_bcf_selected_data = bcf_fgh100mabmd_mbin;
static size_t halow_bcf_selected_len = bcf_fgh100mabmd_mbin_len;
#endif

void mmhal_wlan_select_bcf_for_country(const char *country_code)
{
#ifdef HALOW_CHIP_MM8108
    /* mm8108: only the FGH200MAAMD (CE) BCF is available; no per-country selection yet. */
    (void)country_code;
#else
    /* Mapping per Custom/Common/Lib/mmx108/bcf_bin/bcf_explanation.md */
    if (country_code != NULL && country_code[0] != '\\0' && country_code[1] != '\\0') {
        if ((country_code[0] == 'E' && country_code[1] == 'U') ||
            (country_code[0] == 'I' && country_code[1] == 'N')) {
            halow_bcf_selected_data = bcf_fgh100maamd_mbin;
            halow_bcf_selected_len = bcf_fgh100maamd_mbin_len;
            return;
        }
        /* FCC BCF: AU, KR, NZ, SG, US (and default for others). */
    }
    halow_bcf_selected_data = bcf_fgh100mabmd_mbin;
    halow_bcf_selected_len = bcf_fgh100mabmd_mbin_len;
#endif
}

void mmhal_wlan_read_bcf_file(uint32_t offset, uint32_t requested_len, struct mmhal_robuf *robuf)
{
\tsize_t bcf_len = halow_bcf_selected_len;

    if (bcf_len < offset)
    {
        robuf->len = 0;
        return;
    }

    robuf->buf = halow_bcf_selected_data + offset;
    robuf->len = bcf_len - offset;
    robuf->len = (robuf->len < requested_len) ? robuf->len : requested_len;
}
"""

FW_LOGIC = """
/*
 * ---------------------------------------------------------------------------------------------
 *                                    Firmware Retrieval
 * ---------------------------------------------------------------------------------------------
 */
void mmhal_wlan_read_fw_file(uint32_t offset, uint32_t requested_len, struct mmhal_robuf *robuf)
{
#ifdef HALOW_CHIP_MM8108
\tconst uint8_t *firmware_data = mm8108b2_rl_mbin;
\tuint32_t firmware_len = mm8108b2_rl_mbin_len;
#else
\tconst uint8_t *firmware_data = mm6108_mbin;
\tuint32_t firmware_len = mm6108_mbin_len;
#endif

    if (offset > firmware_len)
    {
        printf("Detected an attempt to start read off the end of the firmware file.\\n");
        robuf->buf = NULL;
        return;
    }

    robuf->buf = firmware_data + offset;
    firmware_len -= offset;

    robuf->len = (firmware_len < requested_len) ? firmware_len : requested_len;
}
"""


def emit_array(out, path, symbol, linkage, static_len):
    data = open(path, "rb").read()
    out.write(f"{linkage + ' ' if linkage else ''}unsigned char {symbol}[] = {{\n")
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        out.write(f"  {chunk},\n")
    out.write("};\n\n")
    lt = "static const" if static_len else "const"
    out.write(f"{lt} unsigned int {symbol}_len = {len(data)};\n\n")


def main():
    out = open("mmhal_wlan_binaries.c", "w", newline="\n")
    out.write(HDR.format(fw_src=MM8108_FW, bcf_src=MM8108_BCF,
                         interim_note=INTERIM_NOTE if INTERIM else ""))
    emit_array(out, MM8108_FW, "mm8108b2_rl_mbin", "", False)
    emit_array(out, "mm6108.mbin", "mm6108_mbin", "const", False)
    # BCFs: only symbols referenced by the selection logic are non-static.
    emit_array(out, MM8108_BCF, MM8108_BCF_SYMBOL, "", False)
    emit_array(out, "bcf_bin/bcf_fgh100mabmd.mbin", "bcf_fgh100mabmd_mbin", "static const", True)
    emit_array(out, "bcf_bin/bcf_fgh100maamd.mbin", "bcf_fgh100maamd_mbin", "static const", True)
    out.write(BCF_LOGIC.replace("@MM8108_BCF_LEN@", MM8108_BCF_SYMBOL + "_len")
                        .replace("@MM8108_BCF@", MM8108_BCF_SYMBOL))
    out.write(FW_LOGIC)
    out.close()
    print(f"generated mmhal_wlan_binaries.c (fw={MM8108_FW}, mm8108 bcf={MM8108_BCF})")


if __name__ == "__main__":
    main()
