/** Copyright 2025 Morse Micro
 *
 * Hostap - Host Interface API
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#ifndef MORSE_COMMANDS_H_
#define MORSE_COMMANDS_H_

#include <linux/types.h>

#define sle16 le16
#define sle32 le32
#define sle64 le64

#ifdef MORSE_WIN_BUILD
#include <windows.h>
#include <winsock2.h>
#endif

#define MORSE_CMD_SEMVER_MAJOR 56
#define MORSE_CMD_SEMVER_MINOR 24
#define MORSE_CMD_SEMVER_PATCH 0

#define MORSE_CMD_TYPE_REQ  BIT(0)
#define MORSE_CMD_TYPE_RESP BIT(1)
#define MORSE_CMD_TYPE_EVT  BIT(2)

#define MORSE_CMD_SSID_MAX_LEN 32
#define MORSE_CMD_MAC_ADDR_LEN 6

enum morse_cmd_id {
	/* Standard commands starting at 0x0000 */
	MORSE_CMD_ID_SET_CHANNEL	    = 0x0001,
	MORSE_CMD_ID_GET_CHANNEL_FULL	    = 0x0013,
	MORSE_CMD_ID_SET_BSS_COLOR	    = 0x0015,
	MORSE_CMD_ID_GET_CHANNEL_DTIM	    = 0x001C,
	MORSE_CMD_ID_GET_CHANNEL	    = 0x001D,
	MORSE_CMD_ID_SET_LONG_SLEEP_CONFIG  = 0x0021,
	MORSE_CMD_ID_STANDBY_MODE	    = 0x0031,
	MORSE_CMD_ID_SET_KEEP_ALIVE_OFFLOAD = 0x0033,

	/* Driver commands starting at 0xA000 */
	MORSE_CMD_ID_DRIVER_START	    = 0xA000,
	MORSE_CMD_ID_SET_S1G_OP_CLASS	    = 0xA007,
	MORSE_CMD_ID_SET_TWT_CONF	    = 0xA010,
	MORSE_CMD_ID_SET_ECSA_S1G_INFO	    = 0xA012,
	MORSE_CMD_ID_CAC		    = 0xA014,
	MORSE_CMD_ID_MBSSID		    = 0xA016,
	MORSE_CMD_ID_SET_MESH_CONFIG	    = 0xA018,
	MORSE_CMD_ID_SET_MCBA_CONF	    = 0xA019,
	MORSE_CMD_ID_DYNAMIC_PEERING_CONFIG = 0xA020,
	MORSE_CMD_ID_CONFIG_RAW		    = 0xA021,
	MORSE_CMD_ID_DRIVER_END,

	/* The get/set parameter command at 0x003E */
	MORSE_CMD_ID_GET_SET_GENERIC_PARAM = 0x003E,
};

/**
 * MAC address structure
 */
struct morse_cmd_mac_addr {
	u8 octet[MORSE_CMD_MAC_ADDR_LEN];
} __attribute__((packed));

/**
 * The header for a command
 * @flags: Flags - used between host and firmware
 * @message_id: Message id - from enum morse_commands_id
 * @len: Command length excluding the header
 * @host_id: Host sequence id - used between host and firmware only
 * @vif_id: Interface id - set by the host and copied into the response
 * @pad: Padding for word alignment
 */
struct morse_cmd_header {
	le16 flags;
	le16 message_id;
	le16 len;
	le16 host_id;
	le16 vif_id;
	le16 pad;
} __attribute__((packed));

/**
 * Setting this value in the `SET_CHANNEL` command will cause the currently configured bandwidth to
 * be used.
 */
#define MORSE_CMD_CHANNEL_BW_NOT_SET 0xFF
/**
 * Setting this value in the `SET_CHANNEL` command will cause the currently configured channel index
 * to be used.
 */
#define MORSE_CMD_CHANNEL_IDX_NOT_SET 0xFF
/**
 * Setting this value in the `SET_CHANNEL` command will cause the currently configured frequency to
 * be used.
 */
#define MORSE_CMD_CHANNEL_FREQ_NOT_SET 0xFFFFFFFF

/**
 * enum morse_cmd_dot11_proto_mode - Used in setting dot11_mode in set_channel
 * @MORSE_CMD_DOT11_PROTO_MODE_AH: 802.11ah S1G mode
 * @MORSE_CMD_DOT11_PROTO_MODE_B: 802.11b (DSSS only) mode
 * @MORSE_CMD_DOT11_PROTO_MODE_BG: 802.11bg (Legacy only) mode
 * @MORSE_CMD_DOT11_PROTO_MODE_GN: 802.11gn (OFDM only) mode
 * @MORSE_CMD_DOT11_PROTO_MODE_BGN: 802.11bgn (Full compatibility) mode
 * @MORSE_CMD_DOT11_PROTO_MODE_INVALID: Invalid mode, PHY is not configured
 */
enum morse_cmd_dot11_proto_mode {
	/** 802.11ah S1G mode */
	MORSE_CMD_DOT11_PROTO_MODE_AH = 0,
	/** 802.11b (DSSS only) mode */
	MORSE_CMD_DOT11_PROTO_MODE_B = 1,
	/** 802.11bg (Legacy only) mode */
	MORSE_CMD_DOT11_PROTO_MODE_BG = 2,
	/** 802.11gn (OFDM only) mode */
	MORSE_CMD_DOT11_PROTO_MODE_GN = 3,
	/** 802.11bgn (Full compatibility) mode */
	MORSE_CMD_DOT11_PROTO_MODE_BGN = 4,
	/** Invalid mode, PHY is not configured */
	MORSE_CMD_DOT11_PROTO_MODE_INVALID = 5,
};

/**
 * struct morse_cmd_req_set_channel - request message for SET_CHANNEL
 * @op_chan_freq_hz: Center frequency of the operating channel
 * @op_bw_mhz: Operating channel bandwidth in MHz
 * @pri_bw_mhz: Primary channel bandwidth in MHz
 * @pri_1mhz_chan_idx: The index of the 1 MHz channel within the operating channel. This is a value
 *                     0 for 1 MHz channel, 0-1 for 2 MHz, 0-3 for 4 MHz, 0-7 for 8 MHz and 0-15 for
 *                     16 MHz.
 * @dot11_mode: enum morse_cmd_dot11_proto_mode
 * @__deprecated_reg_tx_power_set: Deprecated flag (will always be set).
 * @is_off_channel: Indicates that the channel will not be the device's main operating channel.
 *
 * In 802.11ah a BSS supports operating channel widths of 1, 2, 4, 8 and 16 MHz
 * and is required to use a 1 MHz or 2 MHz primary channel width.
 * Additionally 11ah requires that a 1 MHz sub band channel must be available at all
 * operating channel widths regardless of the primary channel width.
 * The location of the 1 MHz channel must be contained within the 1/2 MHz primary channel.
 * The location of the 1 MHz channel within the operating channel can be defined with
 * an integer index.
 *
 * For example, shown is an 8 MHz operating channel with a 2 MHz primary bandwidth
 * and the 1 MHz channel at index 1:
 *
 * | <--------- 8MHz operating channel ----------> | Operating channel
 * | ----4MHz primary----- | ----4MHz secondary--- | 8MHz packet
 * | 2MHz Prim | 2MHz Sec  | --------------------- | 4MHz packet
 * | 2MHz Prim | --------------------------------- | 2MHz packet
 * | --- | 1MH | --------------------------------- | 1MHz packet
 *
 * | -0- | -1- | -2- | -3- | -4- | -5- | -6- | -7- | 1MHz Channel index
 * | ----0---- | ----1---- | ----2---- | ----3---- | 2MHz Channel index
 * | ----------0---------- | ----------1---------- | 4MHz Channel index
 * | ----------------------0---------------------- | 8MHz Channel index
 *
 * The index of the next higher sub band can be calculated by
 * floor(primary_1mhz_channel_index / sub_band_width).
 * E.g. if the 1 MHz channel index is 3, the 2 MHz primary is at floor(3/2) = 1
 */
struct morse_cmd_req_set_channel {
	struct morse_cmd_header hdr;
	le32 op_chan_freq_hz;
	u8 op_bw_mhz;
	u8 pri_bw_mhz;
	u8 pri_1mhz_chan_idx;
	u8 dot11_mode;
	u8 __deprecated_reg_tx_power_set;
	u8 is_off_channel;
} __attribute__((packed));

/**
 * struct morse_cmd_resp_set_channel - response message for SET_CHANNEL
 * @power_qdbm: Power in qdBm
 *
 * Returns the power of the channel set
 */
struct morse_cmd_resp_set_channel {
	struct morse_cmd_header hdr;
	le32 status;
	sle32 power_qdbm;
} __attribute__((packed));

/**
 * struct morse_cmd_req_get_channel - request message for GET_CHANNEL
 *
 * Get the current channel from the firmware
 */
struct morse_cmd_req_get_channel {
	struct morse_cmd_header hdr;
} __attribute__((packed));

/**
 * struct morse_cmd_resp_get_channel - response message for GET_CHANNEL
 * @op_chan_freq_hz: Centre frequency of the operating channel
 * @op_chan_bw_mhz: Operating channel bandwidth in MHz
 * @pri_chan_bw_mhz: Primary channel bandwidth in MHz
 * @pri_1mhz_chan_idx: The index of the 1 MHz channel within the operating channel. This is a value
 *                     0 for 1 MHz channel, 0-1 for 2 MHz, 0-3 for 4 MHz, 0-7 for 8 MHz and 0-15 for
 *                     16 MHz.
 *
 * Confirm message for get current channel
 */
struct morse_cmd_resp_get_channel {
	struct morse_cmd_header hdr;
	le32 status;
	le32 op_chan_freq_hz;
	u8 op_chan_bw_mhz;
	u8 pri_chan_bw_mhz;
	u8 pri_1mhz_chan_idx;
} __attribute__((packed));

/**
 * struct morse_cmd_req_set_bss_color - request message for SET_BSS_COLOR
 * @bss_color: The BSS color
 */
struct morse_cmd_req_set_bss_color {
	struct morse_cmd_header hdr;
	u8 bss_color;
} __attribute__((packed));

/**
 * struct morse_cmd_resp_set_bss_color - response message for SET_BSS_COLOR
 */
struct morse_cmd_resp_set_bss_color {
	struct morse_cmd_header hdr;
	le32 status;
} __attribute__((packed));

/**
 * struct morse_cmd_req_set_long_sleep_config - request message for SET_LONG_SLEEP_CONFIG
 * @enabled: Enable/disable long sleep
 *
 * @note This is used for WNM sleep to enable us to go deaf to traffic
 */
struct morse_cmd_req_set_long_sleep_config {
	struct morse_cmd_header hdr;
	u8 enabled;
} __attribute__((packed));

/**
 * struct morse_cmd_resp_set_long_sleep_config - response message for SET_LONG_SLEEP_CONFIG
 */
struct morse_cmd_resp_set_long_sleep_config {
	struct morse_cmd_header hdr;
	le32 status;
} __attribute__((packed));

/** The maximum length of a user-specified payload (bytes) for Standby status frames */
#define MORSE_CMD_STANDBY_STATUS_FRAME_USER_PAYLOAD_MAX_LEN 64
/** The maximum allowed length of a user filter to apply to wake frames */
#define MORSE_CMD_STANDBY_WAKE_FRAME_USER_FILTER_MAX_LEN 64

/**
 * enum morse_cmd_standby_mode - Return codes for standby mode commands
 * @MORSE_CMD_STANDBY_MODE_EXIT: The external host is indicating that it's now awake
 * @MORSE_CMD_STANDBY_MODE_ENTER: The external host is indicating that it's going into standby mode
 * @MORSE_CMD_STANDBY_MODE_SET_CONFIG_V1: This version of the config command has since been
 *                                        deprecated (see v4 below)
 * @MORSE_CMD_STANDBY_MODE_SET_STATUS_PAYLOAD: The external host provides a payload that gets
 *                                             appended to status frames
 * @MORSE_CMD_STANDBY_MODE_SET_WAKE_FILTER: The external host provides a filter to be applied to
 *                                          incoming standby wake frames
 * @MORSE_CMD_STANDBY_MODE_SET_CONFIG_V2: This version of the config command has since been
 *                                        deprecated (see v4 below)
 * @MORSE_CMD_STANDBY_MODE_SET_CONFIG_V3: This version of the config command has since been
 *                                        deprecated (see v4 below)
 * @MORSE_CMD_STANDBY_MODE_SET_CONFIG_V4: The external host sets a number of configuration options
 *                                        for standby mode
 */
enum morse_cmd_standby_mode {
	/** The external host is indicating that it's now awake */
	MORSE_CMD_STANDBY_MODE_EXIT = 0,
	/** The external host is indicating that it's going into standby mode */
	MORSE_CMD_STANDBY_MODE_ENTER = 1,
	/** This version of the config command has since been deprecated (see v4 below) */
	MORSE_CMD_STANDBY_MODE_SET_CONFIG_V1 = 2,
	/** The external host provides a payload that gets appended to status frames */
	MORSE_CMD_STANDBY_MODE_SET_STATUS_PAYLOAD = 3,
	/** The external host provides a filter to be applied to incoming standby wake frames */
	MORSE_CMD_STANDBY_MODE_SET_WAKE_FILTER = 4,
	/** This version of the config command has since been deprecated (see v4 below) */
	MORSE_CMD_STANDBY_MODE_SET_CONFIG_V2 = 5,
	/** This version of the config command has since been deprecated (see v4 below) */
	MORSE_CMD_STANDBY_MODE_SET_CONFIG_V3 = 6,
	/** The external host sets a number of configuration options for standby mode */
	MORSE_CMD_STANDBY_MODE_SET_CONFIG_V4 = 7,
};

/**
 * enum morse_cmd_standby_mode_exit_reason - Reason for standby mode exit
 * @MORSE_CMD_STANDBY_MODE_EXIT_REASON_NONE: No specific reason for exiting standby mode
 * @MORSE_CMD_STANDBY_MODE_EXIT_REASON_WAKEUP_FRAME: The STA has received the wakeup frame
 * @MORSE_CMD_STANDBY_MODE_EXIT_REASON_ASSOCIATE: The STA needs to (re)associate
 * @MORSE_CMD_STANDBY_MODE_EXIT_REASON_EXT_INPUT: The STA's external input pin has fired
 * @MORSE_CMD_STANDBY_MODE_EXIT_REASON_WHITELIST_PKT: Whitelisted packet received
 * @MORSE_CMD_STANDBY_MODE_EXIT_REASON_TCP_CONNECTION_LOST: TCP connection lost
 * @MORSE_CMD_STANDBY_MODE_EXIT_REASON_HW_SCAN_NOT_ENABLED: HW scan is not enabled
 * @MORSE_CMD_STANDBY_MODE_EXIT_REASON_HW_SCAN_FAILED_TO_START: HW scan failed to start
 * @MORSE_CMD_STANDBY_MODE_EXIT_REASON_MAX: Max exit reason enum value
 */
enum morse_cmd_standby_mode_exit_reason {
	/** No specific reason for exiting standby mode */
	MORSE_CMD_STANDBY_MODE_EXIT_REASON_NONE = 0,
	/** The STA has received the wakeup frame */
	MORSE_CMD_STANDBY_MODE_EXIT_REASON_WAKEUP_FRAME = 1,
	/** The STA needs to (re)associate */
	MORSE_CMD_STANDBY_MODE_EXIT_REASON_ASSOCIATE = 2,
	/** The STA's external input pin has fired */
	MORSE_CMD_STANDBY_MODE_EXIT_REASON_EXT_INPUT = 3,
	/** Whitelisted packet received */
	MORSE_CMD_STANDBY_MODE_EXIT_REASON_WHITELIST_PKT = 4,
	/** TCP connection lost */
	MORSE_CMD_STANDBY_MODE_EXIT_REASON_TCP_CONNECTION_LOST = 5,
	/** HW scan is not enabled */
	MORSE_CMD_STANDBY_MODE_EXIT_REASON_HW_SCAN_NOT_ENABLED = 6,
	/** HW scan failed to start */
	MORSE_CMD_STANDBY_MODE_EXIT_REASON_HW_SCAN_FAILED_TO_START = 7,
	/** Max exit reason enum value */
	MORSE_CMD_STANDBY_MODE_EXIT_REASON_MAX =
		MORSE_CMD_STANDBY_MODE_EXIT_REASON_HW_SCAN_FAILED_TO_START,
};

/**
 * enum morse_cmd_ieee80211_sta_state - IEEE80211 Station State
 */
enum morse_cmd_ieee80211_sta_state {
	MORSE_CMD_IEEE80211_STA_STATE_NOTEXIST		= 0,
	MORSE_CMD_IEEE80211_STA_STATE_NONE		= 1,
	MORSE_CMD_IEEE80211_STA_STATE_AUTHENTICATED	= 2,
	MORSE_CMD_IEEE80211_STA_STATE_ASSOCIATED	= 3,
	MORSE_CMD_IEEE80211_STA_STATE_AUTHORIZED	= 4,
	MORSE_CMD_IEEE80211_STA_STATE_AUTHORIZED_ASLEEP = 5,
};

/**
 * Standby configuration structure
 * @notify_period_s: Interval for transmitting Standby status packets
 * @bss_inactivity_before_deep_sleep_s: Period of inactivity (traffic directed to STA) before
 *                                      external host triggers standby mode
 * @deep_sleep_period_s: Time for firmware to remain in deep sleep in seconds
 * @src_ip: Source IP address
 * @dst_ip: Destination IP address
 * @dst_port: Destination UDP port
 * @pad: Padding for word aligned access in config. (It may grow in future)
 * @disassoc_on_wake: Send a protected disassoc (best effort) to the AP upon a 'wake host' event.
 *                    This will prevent an SA query from the AP upon reconnection to the BSS.
 * @deep_sleep_increment_s: Time in seconds to increment each successive deep sleep
 * @deep_sleep_max_s: Max time to deep sleep for
 * @deep_sleep_scan_iterations: Number of deep sleeps iterations between scans
 */
struct morse_cmd_standby_set_config {
	le32 notify_period_s;
	le32 bss_inactivity_before_deep_sleep_s;
	le32 deep_sleep_period_s;
	le32 src_ip;
	le32 dst_ip;
	le16 dst_port;
	u8 pad[1];
	u8 disassoc_on_wake;
	le32 deep_sleep_increment_s;
	le32 deep_sleep_max_s;
	le32 deep_sleep_scan_iterations;
} __attribute__((packed));

/**
 * Set standby mode status payload structure
 * @len: The length of the payload
 * @payload: The payload
 */
struct morse_cmd_standby_set_status_payload {
	le32 len;
	u8 payload[MORSE_CMD_STANDBY_STATUS_FRAME_USER_PAYLOAD_MAX_LEN];
} __attribute__((packed));

/**
 * Set standby mode enter structure
 * @monitor_bssid: The BSSID to monitor for activity (or lack thereof) before entering deep sleep
 * @is_umac_controlled: Standby mode association is controlled by the UMAC in the chip.
 */
struct morse_cmd_standby_enter {
	struct morse_cmd_mac_addr monitor_bssid;
	u8 is_umac_controlled;
} __attribute__((packed));

/**
 * Set standby mode wake filter structure
 * @len: The length of the wake filter
 * @offset: The offset at which to apply the wake filter
 * @filter: The user-defined filter
 */
struct morse_cmd_standby_set_wake_filter {
	le32 len;
	le32 offset;
	u8 filter[MORSE_CMD_STANDBY_WAKE_FRAME_USER_FILTER_MAX_LEN];
} __attribute__((packed));

/**
 * Standby mode exit response structure
 * @reason: Reason for exiting Standby mode, see @ref morse_cmd_standby_mode_exit_reason
 * @sta_state: Current connection state
 */
struct morse_cmd_standby_mode_exit {
	u8 reason;
	u8 sta_state;
} __attribute__((packed));

/**
 * struct morse_cmd_req_standby_mode - request message for STANDBY_MODE
 * @cmd: Standby Mode subcommands, see @ref morse_cmd_standby_mode
 * @config: Valid for MORSE_CMD_STANDBY_MODE_SET_CONFIG cmd
 * @set_payload: Valid for MORSE_CMD_STANDBY_MODE_SET_STATUS_PAYLOAD cmd
 * @enter: Valid for MORSE_CMD_STANDBY_MODE_ENTER cmd
 * @set_filter: Valid for MORSE_CMD_STANDBY_MODE_SET_WAKE_FILTER cmd
 *
 * Structure for Configuring MM standby mode
 */
struct morse_cmd_req_standby_mode {
	struct morse_cmd_header hdr;
	le32 cmd;
	union {
		u8 opaque[0];
		struct morse_cmd_standby_set_config config;
		struct morse_cmd_standby_set_status_payload set_payload;
		struct morse_cmd_standby_enter enter;
		struct morse_cmd_standby_set_wake_filter set_filter;
	};
} __attribute__((packed));

/**
 * struct morse_cmd_resp_standby_mode - response message for STANDBY_MODE
 *
 * Response structure for MM standby mode command. For status, see @ref morse_cmd_standby_mode.
 */
struct morse_cmd_resp_standby_mode {
	struct morse_cmd_header hdr;
	le32 status;
	union {
		u8 opaque[0];
		struct morse_cmd_standby_mode_exit info;
	};
} __attribute__((packed));

/**
 * struct morse_cmd_req_set_keep_alive_offload - request message for SET_KEEP_ALIVE_OFFLOAD
 * @bss_max_idle_period: The value of the BSS max idle period as it appears in the IE
 * @interpret_as_11ah: Set to TRUE to interpret the value of BSS max idle period as per 11ah spec
 */
struct morse_cmd_req_set_keep_alive_offload {
	struct morse_cmd_header hdr;
	le16 bss_max_idle_period;
	u8 interpret_as_11ah;
} __attribute__((packed));

/**
 * struct morse_cmd_req_set_s1g_op_class - request message for SET_S1G_OP_CLASS
 */
struct morse_cmd_req_set_s1g_op_class {
	struct morse_cmd_header hdr;
	u8 opclass;
	u8 prim_opclass;
} __attribute__((packed));

/**
 * enum morse_cmd_twt_conf_op - Operation codes for the tet config command
 */
enum morse_cmd_twt_conf_op {
	MORSE_CMD_TWT_CONF_OP_CONFIGURE		      = 0,
	MORSE_CMD_TWT_CONF_OP_FORCE_INSTALL_AGREEMENT = 1,
	MORSE_CMD_TWT_CONF_OP_REMOVE_AGREEMENT	      = 2,
	MORSE_CMD_TWT_CONF_OP_CONFIGURE_EXPLICIT      = 3,
};

/**
 * Explicit declaration of the TWT wake interval as expected from WFA
 */
struct morse_cmd_explicit_twt_wake_interval {
	le16 wake_interval_mantissa;
	u8 wake_interval_exponent;
	u8 __padding[5];
} __attribute__((packed));

/**
 * Union of the twt wake interval
 */
union morse_cmd_wake_interval {
	le64 wake_interval_us;
	struct morse_cmd_explicit_twt_wake_interval explicit_twt;
} __attribute__((packed));

/**
 * struct morse_cmd_req_set_twt_conf - request message for SET_TWT_CONF
 * @opcode: TWT subcommands, see @ref morse_cmd_twt_conf_op
 * @flow_id: The flow (twt) identifier for the agreement to set, install or remove
 * @target_wake_time: The target wake time (TSF) for the first TWT service period
 * @wake_interval: Wake interval described explicitly or in usecs
 * @wake_duration_us: Minimum wake duration during TWT service period (usecs)
 * @twt_setup_command: TWT setup command to use (0: request, 1: suggest, 2: demand)
 */
struct morse_cmd_req_set_twt_conf {
	struct morse_cmd_header hdr;
	u8 opcode;
	u8 flow_id;
	le64 target_wake_time;
	union morse_cmd_wake_interval wake_interval;
	le32 wake_duration_us;
	u8 twt_setup_command;
	u8 __padding[3];
} __attribute__((packed));

#define MORSE_CMD_S1G_CAP0_S1G_LONG  BIT(0)
#define MORSE_CMD_S1G_CAP0_SGI_1MHZ  BIT(1)
#define MORSE_CMD_S1G_CAP0_SGI_2MHZ  BIT(2)
#define MORSE_CMD_S1G_CAP0_SGI_4MHZ  BIT(3)
#define MORSE_CMD_S1G_CAP0_SGI_8MHZ  BIT(4)
#define MORSE_CMD_S1G_CAP0_SGI_16MHZ BIT(5)

/**
 * struct morse_cmd_req_set_ecsa_s1g_info - request message for SET_ECSA_S1G_INFO
 * @operating_channel_freq_hz: Operating Channel Frequency Hz. Endianness __le32 op_chan_freq_hz is
 *                             not considered as the cmd is indicated to driver and not chip.
 * @opclass: Global operating class
 * @primary_channel_bw_mhz: Primary channel bw in MHz
 * @prim_1mhz_ch_idx: 1MHz channel index
 * @operating_channel_bw_mhz: Operating channel bandwidth in MHz
 * @prim_opclass: Global operating class for primary chan
 */
struct morse_cmd_req_set_ecsa_s1g_info {
	struct morse_cmd_header hdr;
	le32 operating_channel_freq_hz;
	u8 opclass;
	u8 primary_channel_bw_mhz;
	u8 prim_1mhz_ch_idx;
	u8 operating_channel_bw_mhz;
	u8 prim_opclass;
	u8 s1g_cap0;
	u8 s1g_cap1;
	u8 s1g_cap2;
	u8 s1g_cap3;
} __attribute__((packed));

#define MORSE_CMD_CAC_CFG_CHANGE_RULE_MAX 8
#define MORSE_CMD_CAC_CFG_ARFS_MAX	  99
#define MORSE_CMD_CAC_CFG_CHANGE_MAX	  99
#define MORSE_CMD_CAC_CFG_CHANGE_STEP	  5

/**
 * enum morse_cmd_cac_op - CAC command operation codes
 */
enum morse_cmd_cac_op {
	MORSE_CMD_CAC_OP_DISABLE = 0,
	MORSE_CMD_CAC_OP_ENABLE	 = 1,
	MORSE_CMD_CAC_OP_CFG_GET = 2,
	MORSE_CMD_CAC_OP_CFG_SET = 3,
};

/**
 * CAC threshold change rule
 * @arfs: Threshold in Authentication Request Frames per Second
 * @threshold_change: Percentage change to apply to threshold if condition is matched
 */
struct morse_cmd_cac_change_rule {
	le16 arfs;
	sle16 threshold_change;
} __attribute__((packed));

/**
 * struct morse_cmd_req_cac - request message for CAC
 * @opcode: CAC subcommand @ref morse_cmd_cac_op
 * @rule_tot: Number of threshold change rules
 * @rule: Threshold change rule (%)
 */
struct morse_cmd_req_cac {
	struct morse_cmd_header hdr;
	u8 opcode;
	u8 rule_tot;
	struct morse_cmd_cac_change_rule rule[MORSE_CMD_CAC_CFG_CHANGE_RULE_MAX];
} __attribute__((packed));

/**
 * struct morse_cmd_resp_cac - response message for CAC
 * @rule_tot: Number of threshold change rules
 * @rule: Threshold change rule (%)
 */
struct morse_cmd_resp_cac {
	struct morse_cmd_header hdr;
	le32 status;
	u8 rule_tot;
	struct morse_cmd_cac_change_rule rule[MORSE_CMD_CAC_CFG_CHANGE_RULE_MAX];
} __attribute__((packed));

#define MORSE_CMD_IFNAMSIZ 16

/**
 * struct morse_cmd_req_mbssid - request message for MBSSID
 * @max_bssid_indicator: Maximum supported BSS to be updated in MBSSID IE
 * @transmitter_iface: Beacon or probe reponse transmitting interface name
 */
struct morse_cmd_req_mbssid {
	struct morse_cmd_header hdr;
	u8 max_bssid_indicator;
	s8 transmitter_iface[MORSE_CMD_IFNAMSIZ];
} __attribute__((packed));

#define MORSE_CMD_MESH_ID_LEN_MAX	       32
#define MORSE_CMD_MESH_BEACONLESS_MODE_DISABLE 0
#define MORSE_CMD_MESH_BEACONLESS_MODE_ENABLE  1
#define MORSE_CMD_MESH_PEER_LINKS_MIN	       0
#define MORSE_CMD_MESH_PEER_LINKS_MAX	       20

/**
 * struct morse_cmd_req_set_mesh_config - request message for SET_MESH_CONFIG
 * @mesh_id_len: Mesh ID Len
 * @mesh_id: Mesh ID, equivalent to SSID in infra
 * @mesh_beaconless_mode: Mesh beaconless mode enabled/disabled
 * @max_plinks: Maximum number of peer links
 *
 * Structure derived from struct morse_mesh_config in morse.h in the driver
 */
struct morse_cmd_req_set_mesh_config {
	struct morse_cmd_header hdr;
	u8 mesh_id_len;
	u8 mesh_id[MORSE_CMD_MESH_ID_LEN_MAX];
	u8 mesh_beaconless_mode;
	u8 max_plinks;
} __attribute__((packed));

/**
 * struct morse_cmd_req_set_mcba_conf - request message for SET_MCBA_CONF
 * @mbca_config: Configuration to enable or disable MBCA TBTT Selection and Adjustment
 * @beacon_timing_report_interval: Beacon Timing Element Report interval
 * @min_beacon_gap_ms: Minimum gap between our beacon and neighbor beacons
 * @mbss_start_scan_duration_ms: Initial scan duration to find neighbor mesh peers in the MBSS
 * @tbtt_adj_interval_ms: TBTT adjustment timer interval in LMAC firmware
 */
struct morse_cmd_req_set_mcba_conf {
	struct morse_cmd_header hdr;
	u8 mbca_config;
	u8 beacon_timing_report_interval;
	u8 min_beacon_gap_ms;
	le16 mbss_start_scan_duration_ms;
	le16 tbtt_adj_interval_ms;
} __attribute__((packed));

/**
 * struct morse_cmd_req_dynamic_peering_config - request message for DYNAMIC_PEERING_CONFIG
 * @enabled: Enable or disable mesh dynamic peering
 * @rssi_margin: RSSI margin to consider while selecting a peer to kick out
 * @blacklist_timeout: Kicked out peer is not allowed connection during this period
 */
struct morse_cmd_req_dynamic_peering_config {
	struct morse_cmd_header hdr;
	u8 enabled;
	u8 rssi_margin;
	le32 blacklist_timeout;
} __attribute__((packed));

#define MORSE_CMD_CFG_RAW_FLAG_ENABLE  BIT(0)
#define MORSE_CMD_CFG_RAW_FLAG_DELETE  BIT(1)
#define MORSE_CMD_CFG_RAW_FLAG_UPDATE  BIT(2)
#define MORSE_CMD_CFG_RAW_FLAG_DYNAMIC BIT(3)
/** RAW special AID to reserve the medium for DCS */
#define MORSE_CMD_RAW_RESERVED_AID_DCS 2008
/** RAW special AID to reserve the medium for AP's downlink */
#define MORSE_CMD_RAW_RESERVED_AID_DOWNLINK 2009

/**
 * enum morse_cmd_raw_tlv_tag - Tags for the RAW TLV
 */
enum morse_cmd_raw_tlv_tag {
	MORSE_CMD_RAW_TLV_TAG_SLOT_DEF	 = 0,
	MORSE_CMD_RAW_TLV_TAG_GROUP	 = 1,
	MORSE_CMD_RAW_TLV_TAG_START_TIME = 2,
	MORSE_CMD_RAW_TLV_TAG_PRAW	 = 3,
	MORSE_CMD_RAW_TLV_TAG_BCN_SPREAD = 4,
	MORSE_CMD_RAW_TLV_TAG_DYN_GLOBAL = 5,
	MORSE_CMD_RAW_TLV_TAG_DYN_CONFIG = 6,
	MORSE_CMD_RAW_TLV_TAG_LAST	 = 7,
};

/**
 * Slot definition is required for new raw configs
 * @raw_duration_us: Total length of the RAW window. @ref raw_duration_us / num_slots =
 *                   slot_duration
 * @num_slots: Number of individual "slots" within the RAW window
 */
struct morse_cmd_raw_tlv_slot_def {
	u8 tag;
	le32 raw_duration_us;
	u8 num_slots;
	u8 cross_slot_bleed;
} __attribute__((packed));

/**
 * RAW group information
 * @aid_start: Start AID for this raw config
 * @aid_end: End AID for this config (inclusive)
 */
struct morse_cmd_raw_tlv_group {
	u8 tag;
	le16 aid_start;
	le16 aid_end;
} __attribute__((packed));

/**
 * RAW start time information
 * @start_time_us: Time the RAW window starts, measured from the end of the frame carrying RPS IE
 */
struct morse_cmd_raw_tlv_start_time {
	u8 tag;
	le32 start_time_us;
} __attribute__((packed));

/**
 * Periodic RAW information
 */
struct morse_cmd_raw_tlv_praw {
	u8 tag;
	u8 periodicity;
	u8 validity;
	u8 start_offset;
	u8 refresh_on_expiry;
} __attribute__((packed));

/**
 * RAW beacon spreading information
 */
struct morse_cmd_raw_tlv_bcn_spread {
	u8 tag;
	le16 max_spread;
	le16 nominal_sta_per_bcn;
} __attribute__((packed));

/**
 * Global configuration for dynamic RAW configuration
 * @num_configs: Number of dynamic RAW confgis present
 * @num_bcn_indexes: The maximum number of beacon frames to add RAW configs to
 */
struct morse_cmd_raw_tlv_dyn_global {
	u8 tag;
	le16 num_configs;
	le16 num_bcn_indexes;
} __attribute__((packed));

/**
 * Single dynamic RAW config entry in the batch of RAW configs
 * @id: Unique config id of dynamic RAW config entry
 * @index: Index of beacon to include this RAW config into
 * @len: Length of RAW config
 * @variable: RAW TLV data
 */
struct morse_cmd_raw_tlv_dyn_config {
	u8 tag;
	le16 id;
	le16 index;
	le16 len;
	u8 variable[];
} __attribute__((packed));

/**
 * RAW TLV data
 */
union morse_cmd_raw_tlvs {
	u8 tag;
	struct morse_cmd_raw_tlv_slot_def slot_def;
	struct morse_cmd_raw_tlv_group group;
	struct morse_cmd_raw_tlv_start_time start_time;
	struct morse_cmd_raw_tlv_praw praw;
	struct morse_cmd_raw_tlv_bcn_spread bcn_spread;
	struct morse_cmd_raw_tlv_dyn_global dyn_global;
	struct morse_cmd_raw_tlv_dyn_config dyn_config;
} __attribute__((packed));

/**
 * struct morse_cmd_req_config_raw - request message for CONFIG_RAW
 * @flags: Flags for this RAW config
 * @id: ID to reference this RAW config. If ID already exists, existing config will be overwritten.
 *      ID of 0 is reserved to indicate operate on RAW globally.
 * @variable: RAW TLV data
 */
struct morse_cmd_req_config_raw {
	struct morse_cmd_header hdr;
	le32 flags;
	le16 id;
	u8 variable[];
} __attribute__((packed));

#define MORSE_CMD_HOST_BLOCK_TX_FRAMES BIT(0)
#define MORSE_CMD_HOST_BLOCK_TX_CMD    BIT(1)

/**
 * enum morse_cmd_param_action - Actions to take on the param
 */
enum morse_cmd_param_action {
	MORSE_CMD_PARAM_ACTION_SET  = 0,
	MORSE_CMD_PARAM_ACTION_GET  = 1,
	MORSE_CMD_PARAM_ACTION_LAST = 2,
};

/**
 * enum morse_cmd_slow_clock_mode - Different slow clock source selection modes
 * @MORSE_CMD_SLOW_CLOCK_MODE_AUTO: Slow clock source would be automatically selected
 * @MORSE_CMD_SLOW_CLOCK_MODE_INTERNAL: Slow clock source would be set to internal
 */
enum morse_cmd_slow_clock_mode {
	/** Slow clock source would be automatically selected */
	MORSE_CMD_SLOW_CLOCK_MODE_AUTO = 0,
	/** Slow clock source would be set to internal */
	MORSE_CMD_SLOW_CLOCK_MODE_INTERNAL = 1,
};

/**
 * enum morse_cmd_param_id - Subcommand IDs for generic get / set command
 * @MORSE_CMD_PARAM_ID_AUTOCONNECT: Automatically reconnect if connection is lost (FullMAC only).
 */
enum morse_cmd_param_id {
	MORSE_CMD_PARAM_ID_MAX_TRAFFIC_DELIVERY_WAIT_US	  = 0,
	MORSE_CMD_PARAM_ID_EXTRA_ACK_TIMEOUT_ADJUST_US	  = 1,
	MORSE_CMD_PARAM_ID_TX_STATUS_FLUSH_WATERMARK	  = 2,
	MORSE_CMD_PARAM_ID_TX_STATUS_FLUSH_MIN_AMPDU_SIZE = 3,
	MORSE_CMD_PARAM_ID_POWERSAVE_TYPE		  = 4,
	MORSE_CMD_PARAM_ID_SNOOZE_DURATION_ADJUST_US	  = 5,
	MORSE_CMD_PARAM_ID_TX_BLOCK			  = 6,
	MORSE_CMD_PARAM_ID_FORCED_SNOOZE_PERIOD_US	  = 7,
	MORSE_CMD_PARAM_ID_WAKE_ACTION_GPIO		  = 8,
	MORSE_CMD_PARAM_ID_WAKE_ACTION_GPIO_PULSE_MS	  = 9,
	MORSE_CMD_PARAM_ID_CONNECTION_MONITOR_GPIO	  = 10,
	MORSE_CMD_PARAM_ID_INPUT_TRIGGER_GPIO		  = 11,
	MORSE_CMD_PARAM_ID_INPUT_TRIGGER_MODE		  = 12,
	MORSE_CMD_PARAM_ID_COUNTRY			  = 13,
	MORSE_CMD_PARAM_ID_RTS_THRESHOLD		  = 14,
	MORSE_CMD_PARAM_ID_HOST_TX_BLOCK		  = 15,
	MORSE_CMD_PARAM_ID_MEM_RETENTION_CODE		  = 16,
	MORSE_CMD_PARAM_ID_NON_TIM_MODE			  = 17,
	MORSE_CMD_PARAM_ID_DYNAMIC_PS_TIMEOUT_MS	  = 18,
	MORSE_CMD_PARAM_ID_HOME_CHANNEL_DWELL_MS	  = 19,
	MORSE_CMD_PARAM_ID_SLOW_CLOCK_MODE		  = 20,
	MORSE_CMD_PARAM_ID_FRAGMENT_THRESHOLD		  = 21,
	MORSE_CMD_PARAM_ID_BEACON_LOSS_COUNT		  = 22,
	MORSE_CMD_PARAM_ID_AP_POWER_SAVE		  = 23,
	MORSE_CMD_PARAM_ID_BEACON_OFFLOAD		  = 24,
	MORSE_CMD_PARAM_ID_PROBE_RESP_OFFLOAD		  = 25,
	MORSE_CMD_PARAM_ID_BSS_MAX_AWAY_DURATION	  = 26,
	MORSE_CMD_PARAM_ID_DEFAULT_ACTIVE_SCAN_DWELL_MS	  = 27,
	MORSE_CMD_PARAM_ID_CTS_TO_SELF			  = 28,
	MORSE_CMD_PARAM_ID_CHANNELIZATION		  = 29,
	MORSE_CMD_PARAM_ID_CRYPTO_IN_HOST		  = 30,
	/** Automatically reconnect if connection is lost (FullMAC only). */
	MORSE_CMD_PARAM_ID_AUTOCONNECT = 31,
	MORSE_CMD_PARAM_ID_LAST	       = 32,
};

/**
 * struct morse_cmd_req_get_set_generic_param - request message for GET_SET_GENERIC_PARAM
 * @param_id: The param to perform the action on [enum morse_cmd_param_id]
 * @action: The action to take on the param [get | set]
 * @flags: Any flags to modify the behavior of the action (for forwards/backwards compatibility)
 * @value: The value to set (only applicable for set actions)
 */
struct morse_cmd_req_get_set_generic_param {
	struct morse_cmd_header hdr;
	le32 param_id;
	le32 action;
	le32 flags;
	le32 value;
} __attribute__((packed));

/**
 * struct morse_cmd_resp_get_set_generic_param - response message for GET_SET_GENERIC_PARAM
 * @flags: Any flags to signal change of interpretation of response - forwards / backwards
 *         compatibility
 * @value: The value returned (only applicable for get actions)
 */
struct morse_cmd_resp_get_set_generic_param {
	struct morse_cmd_header hdr;
	le32 status;
	le32 flags;
	le32 value;
} __attribute__((packed));

#endif // MORSE_COMMANDS_H_
