/*
 * Copyright 2024 Morse Micro
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-MorseMicroCommercial
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 *
 * Note: this file contains function definitions and therefore must only be included once from
 *       a single C source file.
 */
#include "hw_scan_fsm.h"

#define HW_SCAN_FSM_INITIAL_STATE HW_SCAN_FSM_STATE_INACTIVE


#ifndef HW_SCAN_FSM_LOG
#define HW_SCAN_FSM_LOG(format_str, ...) \
    do {                                 \
        (void)format_str;                \
    } while (0)
#endif


static void hw_scan_fsm_inactive_entry(struct hw_scan_fsm_instance *inst,
                                       enum hw_scan_fsm_state prev_state);
static void hw_scan_fsm_in_progress_entry(struct hw_scan_fsm_instance *inst,
                                          enum hw_scan_fsm_state prev_state);


static void hw_scan_fsm_req_abort(struct hw_scan_fsm_instance *inst, enum hw_scan_fsm_event event);

static void hw_scan_fsm_scan_aborted(struct hw_scan_fsm_instance *inst,
                                     enum hw_scan_fsm_event event);

static void hw_scan_fsm_scan_done(struct hw_scan_fsm_instance *inst, enum hw_scan_fsm_event event);



static void hw_scan_fsm_transition_error(struct hw_scan_fsm_instance *inst,
                                         enum hw_scan_fsm_event event);

static void hw_scan_fsm_reentrance_error(struct hw_scan_fsm_instance *inst);



typedef void (*hw_scan_fsm_callback_t)(struct hw_scan_fsm_instance *inst,
                                       enum hw_scan_fsm_event event);

struct hw_scan_fsm_table_row
{
    uint32_t from_states;
    uint32_t events;
    enum hw_scan_fsm_state to_state;
    hw_scan_fsm_callback_t callback;
};

const struct hw_scan_fsm_table_row hw_scan_fsm_table[] = {
    {
        .from_states = HW_SCAN_FSM_STATE_IN_PROGRESS_MASK,
        .events = HW_SCAN_FSM_EVENT_ABORT_ACTIVE_MASK | HW_SCAN_FSM_EVENT_ABORT_ALL_MASK,
        .to_state = HW_SCAN_FSM_STATE_ABORT_PENDING,
        .callback = hw_scan_fsm_req_abort,
    },
    {
        .from_states = HW_SCAN_FSM_STATE_ABORT_PENDING_MASK,
        .events = HW_SCAN_FSM_EVENT_ABORT_ACTIVE_MASK | HW_SCAN_FSM_EVENT_ABORT_ALL_MASK,
        .to_state = HW_SCAN_FSM_STATE_ABORT_PENDING,
        .callback = NULL,
    },
    {
        .from_states = HW_SCAN_FSM_STATE_ABORT_PENDING_MASK | HW_SCAN_FSM_STATE_IN_PROGRESS_MASK,
        .events = HW_SCAN_FSM_EVENT_DONE_MASK,
        .to_state = HW_SCAN_FSM_STATE_IN_PROGRESS,
        .callback = hw_scan_fsm_scan_done,
    },
    {
        .from_states = HW_SCAN_FSM_STATE_ABORT_PENDING_MASK | HW_SCAN_FSM_STATE_IN_PROGRESS_MASK,
        .events = HW_SCAN_FSM_EVENT_ABORT_MASK,
        .to_state = HW_SCAN_FSM_STATE_IN_PROGRESS,
        .callback = hw_scan_fsm_scan_aborted,
    },
    {
        .from_states = HW_SCAN_FSM_STATE_INACTIVE_MASK,
        .events = HW_SCAN_FSM_EVENT_REQUEST_MASK,
        .to_state = HW_SCAN_FSM_STATE_IN_PROGRESS,
        .callback = NULL,
    },
    {
        .from_states = HW_SCAN_FSM_STATE_IN_PROGRESS_MASK,
        .events = HW_SCAN_FSM_EVENT_COMPLETE_NO_PENDING_MASK,
        .to_state = HW_SCAN_FSM_STATE_INACTIVE,
        .callback = NULL,
    },
    {
        .from_states = HW_SCAN_FSM_STATE_INACTIVE_MASK,
        .events = HW_SCAN_FSM_EVENT_ABORT_ALL_MASK,
        .to_state = HW_SCAN_FSM_STATE_INACTIVE,
        .callback = NULL,
    },
};

#define HW_SCAN_FSM_TABLE_N_ENTRIES 7


static inline const char *hw_scan_fsm_state_tostr(enum hw_scan_fsm_state state)
{
    switch (state)
    {
        case 0:
            return "NONE";
        case HW_SCAN_FSM_STATE_INACTIVE:
            return "inactive";
        case HW_SCAN_FSM_STATE_IN_PROGRESS:
            return "in_progress";
        case HW_SCAN_FSM_STATE_ABORT_PENDING:
            return "abort_pending";
        default:
            return "??";
    }
}

static inline const char *hw_scan_fsm_event_tostr(enum hw_scan_fsm_event event)
{
    switch (event)
    {
        case 0:
            return "INVALID";
        case HW_SCAN_FSM_EVENT_REQUEST:
            return "request";
        case HW_SCAN_FSM_EVENT_DONE:
            return "done";
        case HW_SCAN_FSM_EVENT_ABORT:
            return "abort";
        case HW_SCAN_FSM_EVENT_COMPLETE_NO_PENDING:
            return "complete_no_pending";
        case HW_SCAN_FSM_EVENT_ABORT_ACTIVE:
            return "abort_active";
        case HW_SCAN_FSM_EVENT_ABORT_ALL:
            return "abort_all";
        default:
            return "??";
    }
}

static void hw_scan_fsm_handle_event_internal(struct hw_scan_fsm_instance *inst,
                                              enum hw_scan_fsm_event event)
{
    uint32_t ii;

    uint32_t current_state_mask = 1ul << inst->current_state;
    uint32_t event_mask = 1ul << event;

    for (ii = 0; ii < HW_SCAN_FSM_TABLE_N_ENTRIES; ii++)
    {
        const struct hw_scan_fsm_table_row *row = &hw_scan_fsm_table[ii];
        if ((row->from_states & current_state_mask) && (row->events & event_mask))
        {
            HW_SCAN_FSM_LOG("Event %s in state %s -> %s / %p\n",
                            hw_scan_fsm_event_tostr(event),
                            hw_scan_fsm_state_tostr(inst->current_state),
                            hw_scan_fsm_state_tostr(row->to_state),
                            row->callback);

            if (row->callback)
            {
                row->callback(inst, event);
            }
            if (row->to_state != HW_SCAN_FSM_STATE_NONE)
            {
                enum hw_scan_fsm_state prev_state = inst->current_state;
                switch (prev_state)
                {
                    default:
                        break;
                }

                inst->current_state = row->to_state;

                switch (inst->current_state)
                {
                    case HW_SCAN_FSM_STATE_INACTIVE:
                        hw_scan_fsm_inactive_entry(inst, prev_state);
                        break;
                    case HW_SCAN_FSM_STATE_IN_PROGRESS:
                        hw_scan_fsm_in_progress_entry(inst, prev_state);
                        break;
                    default:
                        break;
                }
            }
            return;
        }
    }
    hw_scan_fsm_transition_error(inst, event);
}


void hw_scan_fsm_handle_event(struct hw_scan_fsm_instance *inst, enum hw_scan_fsm_event event)
{
    if (inst->in_event_handler)
    {
        if (inst->pending_event != HW_SCAN_FSM_EVENT_NONE)
        {
            hw_scan_fsm_reentrance_error(inst);
        }
        else
        {
            inst->pending_event = event;
        }
        return;
    }

    inst->in_event_handler = true;

    while (event != HW_SCAN_FSM_EVENT_NONE)
    {
        hw_scan_fsm_handle_event_internal(inst, event);
        event = inst->pending_event;
        inst->pending_event = HW_SCAN_FSM_EVENT_NONE;
    }

    inst->in_event_handler = false;
}
