/*
 * Copyright 2024 Morse Micro
 * SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-MorseMicroCommercial
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */



#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


enum hw_scan_fsm_state
{
    HW_SCAN_FSM_STATE_NONE,
    HW_SCAN_FSM_STATE_INACTIVE,
    HW_SCAN_FSM_STATE_IN_PROGRESS,
    HW_SCAN_FSM_STATE_ABORT_PENDING,
};


enum hw_scan_fsm_state_mask
{
    HW_SCAN_FSM_STATE_INACTIVE_MASK = (1ul << HW_SCAN_FSM_STATE_INACTIVE),
    HW_SCAN_FSM_STATE_IN_PROGRESS_MASK = (1ul << HW_SCAN_FSM_STATE_IN_PROGRESS),
    HW_SCAN_FSM_STATE_ABORT_PENDING_MASK = (1ul << HW_SCAN_FSM_STATE_ABORT_PENDING),
};


enum hw_scan_fsm_event
{
    HW_SCAN_FSM_EVENT_NONE,
    HW_SCAN_FSM_EVENT_REQUEST,
    HW_SCAN_FSM_EVENT_DONE,
    HW_SCAN_FSM_EVENT_ABORT,
    HW_SCAN_FSM_EVENT_COMPLETE_NO_PENDING,
    HW_SCAN_FSM_EVENT_ABORT_ACTIVE,
    HW_SCAN_FSM_EVENT_ABORT_ALL,
};


enum hw_scan_fsm_event_mask
{
    HW_SCAN_FSM_EVENT_REQUEST_MASK = (1ul << HW_SCAN_FSM_EVENT_REQUEST),
    HW_SCAN_FSM_EVENT_DONE_MASK = (1ul << HW_SCAN_FSM_EVENT_DONE),
    HW_SCAN_FSM_EVENT_ABORT_MASK = (1ul << HW_SCAN_FSM_EVENT_ABORT),
    HW_SCAN_FSM_EVENT_COMPLETE_NO_PENDING_MASK = (1ul << HW_SCAN_FSM_EVENT_COMPLETE_NO_PENDING),
    HW_SCAN_FSM_EVENT_ABORT_ACTIVE_MASK = (1ul << HW_SCAN_FSM_EVENT_ABORT_ACTIVE),
    HW_SCAN_FSM_EVENT_ABORT_ALL_MASK = (1ul << HW_SCAN_FSM_EVENT_ABORT_ALL),
};


struct hw_scan_fsm_instance
{

    enum hw_scan_fsm_state current_state;

    volatile bool in_event_handler;

    enum hw_scan_fsm_event pending_event;

    void *arg;
};


#define HW_SCAN_FSM_INSTANCE_INIT                    \
    {                                                \
        .current_state = HW_SCAN_FSM_STATE_INACTIVE, \
        .in_event_handler = false,                   \
        .pending_event = HW_SCAN_FSM_EVENT_NONE,     \
        .arg = NULL,                                 \
    }


static inline void hw_scan_fsm_init(struct hw_scan_fsm_instance *inst)
{
    static const struct hw_scan_fsm_instance inst_init = HW_SCAN_FSM_INSTANCE_INIT;
    *inst = inst_init;
}


void hw_scan_fsm_handle_event(struct hw_scan_fsm_instance *inst, enum hw_scan_fsm_event event);


